* Death Race 2000
by
Steve Ralph

"The Karakoram Highway is like a cassette tape strewn across
a building site"   Robin Dennell.

We stood on the side of the road. Our driver was on his back
at the front of the vehicle with only his legs protruding. We
wished that he would fall asleep and stay asleep for at least
another four hours, but our hopes were dashed by the occasional
grunt and the tinkle of a spanner.  Our driver was of the opinion
that no sleep for two days was no problem.

Brightly lit vehicles moved up and down the artery, the
vivid patterns on their flank like an arcane genetic code. A
thousand or so feet below, the waters of the Indus waited
greedily for a driver to make one last mistake.

The second vehicle arrived, and within minutes the wheels
spun on the gravel creating a huge dust cloud which attached
itself to the back of the van.

One hour from Islamabad there was a crunch and it broke
down. As the driver walked back to Islamabad to get a part, we
went in search of breakfast but found a Buddhist Temple instead.
The Moslems had knocked the heads off the Buddhas. Even though we
didn't look like Buddhists we decided not to take any chances and
beat a hasty retreat. Apart from that,temples didn't do eggs. The
culture shock was setting in. After little sleep on the plane and
only a day in Islamabad and the British Embassy Club, we had
hardly acclimatised.

Our driver returned with a new transmission link and we knew
that this one was OK because it did not have a welded fracture
down the middle. We progressed towards the mountains, through a
strange land where everybody wore the same clothes and there were
no women in the streets and it was even hotter than Skegness. Our
driver's techniques in built up areas began to arouse our
interest. Foot on accelerator, hand on horn, it is the Will of
Allah if you don't move out of the way.

After a tea stop in a place called Beshum, things changed
abruptly. The road along the bottom of the pleasant valley, with
steep crumbling sides above, suddenly became the road half way up
the mother of all gorges, with steep crumbling slopes below. The
road twisted and turned like a demented python. Our driver's
cornering technique  foot down, horn on...  began to cause
serious concern, as did his tendency to race anything that
overtook. Occasionally he would stop, point down and say "Ten
men" or "Five men". I wondered why we were never driven over the
edge of the Karakoram Highway.

The Indus gorge is huge by European standards. The initial
section of the Highway travels up this immense feature for maybe
a hundred miles. It has a distinctly temporary  in geological
terms  feel to it and at many places we encountered landslips.
Time has used the sharp blade of the Indus, swollen with glacial
melt, to slice through the moraine rubble, leaving a great chasm
to drain the Western Karakoram. Then somebody decided that a road
along its walls would be a good idea.

Respite came at last when we found ourselves at a village.
We stopped and went into a restaurant.
	"Ah" said Uncle Tom, "It's the restaurant at the end of the
Universe."

	We ate our curry and chappaties. The curry was delicious.

We set off again  foot down, horn on...  We told our driver
to drive more slowly. He agreed   and promptly accelerated. The
next hour is indelibly etched in my memory. The Highway has a
grand rhythm. An experienced driver senses the rhythm and will
drive safely at a good pace. Ours was simply going too fast. The
motion was becoming unstable. Each swing, each last second
braking, each overtaking, brought us closer to the point of final
instability. Somebody's comment, that with a good launch we could
expect between five and six seconds of free fall before impact,
did not help. The drop to our left took on the aspect of the
Reaper's Scythe. Each of was in a private hell, convinced we
would never see our beautiful peak, let alone climb it.

	"Slow down," we shouted.
	"Yes," he cried   and accelerated again.

	We careered round a double bend to meet a lorry like a squat
brightly coloured bug coming towards us. The resulting manoeuvre
made the back of the van drift. The string snapped and as one, we
leapt up in our seats screaming "STOP!" He refused.

Suddenly there was an awful noise from the back. Rickets,
the retired  at twenty one  coal miner from Barnsley was
obviously in severe pain. His features contorted, he grasped his
stomach in agony and made awful retching sounds. This did finally
convince the driver to stop. Rickets recovered suddenly and leapt
out, quickly followed by the rest of us. Things got very fraught
when we refused to travel any further until the driver had rested
- it emerged that he hadn't in fact slept for two days - and he
said he was going on with or without us, as he consumed a huge
lump of local "medicine".

Eventually we reached a compromise. We would travel in a
lorry we had flagged down and the van would travel behind us. Our
friend The Survivor, being brave, would stay in the van for
security's sake. Ten seconds after starting, the van overtook and
the Survivor screamed for help out of the window with a pleading
look on his face.

	"No worry" said the lorry driver, "Soon he sleep."
	We enquired as to the source of this insight.
	"We gave him opium cigarette!"

A few miles later we found a shaky Survivor, a van, and the
driver trying to mend the fan belt with a piece of string. This
is in fact impossible, but he refused to be beaten. A spare from
a passing van eventually cured it. We were leaving the gorge now
and entering a strange desert plateau, ringed with arid mountains.
The free fall time was now down to half a second but by
now we were too numb to feel any terror.

Eventually he pulled into the side of the road.
	"I sleep."

He was out for five hours. We dozed in the desert, watching
the miracle of the dawn we had scarcely expected to see.

Arriving in Gilgit we parked in the main street. A fierce
man came towards us and grabbed the driver by the throat. He
dragged him out of the cab and the last we saw of him was his
being punched and kicked down the street. The fierce man returned
and drove us carefully, sedately and with consummate skill to the
refuge of the Hunza Inn. The story of how the Sahibs had gone on
strike had travelled on ahead of us.

Well, Rickets and his climbing partner The Cowboy made the
first ascent of our beautiful peak and The Sheffield Karakoram
Expedition was a resounding success, but that is another story.
