* Sentimental Ramblings of an Early Club Member
by
Kate Fowler or Kate Peek, to many

The last time I visited The Castle Mountaineering Club
clubroom was in August 1986, during a hectic trip to England to
put our house up for sale, pack belongings, and say farewell to
family and friends. Alan and I had decided to settle in Norway
after an initial two year contract and the reason we'd taken the
temporary appointment in the first place had, I believe, much to
do with the CMC. More than twenty years ago, only a few months
after the Club was founded, I became an official paid up member
and apart from honorary members, I believe Mike Anderson and I
are now the longest standing Club members. From that time on my
love for the hills and wild open spaces grew  hence the prospect
of new hills, combined with months of skiing was too great to
turn down.

My experiences have ranged from early attempts at rock
climbing, being more or less hauled up Diffs on Froggatt, moist
struggles up "The Buachaille" from the warmth and  in those days
squalor of Lagangarbh, suicidal snow ploughs in white outs down
the White Lady on Cairngorm and dirty bog trotting days on
Kinder, to classic climbs in Llanberis, back packing in the
remoter parts of the Scottish Highlands, summer holidays in the
French Alps and now, the thrills and pleasure of Langrenn skiing
over mountains, through forests  and even on the sea in a good
winter , for several months of the year.

I have no claims to great conquests, either on rock or hill.
I've never been one for seeking the highest, fastest or hardest
and my one attempt at outdoor competitiveness was a farce. This
was the first Edale Skyline Race and the late Don Morrison
cajoled me into entering.

	"You're fit," he said.

Well, I'd not run anywhere for nearly fifteen years and I
was, in those days, a very heavy smoker! I came in last  OK, many
had dropped out by the wayside  and when I arrived back at Edale,
nearly everyone had packed up and gone home. A voice from the
darkness cried:

	"Well done Kate, you've come second in the ladies section."

	Now, there were only four to start with and two of those had
dropped out!

My only connection with anything remotely organized on rock
and hill is that I did decide to tackle the Munros: I had in fact
just reached a little over half way with my Munros when we
emigrated to Norway and I haven't completely given up the idea of
finishing them completely one day. Even the ones I tackled were
often attempted in a very come day go day fashion: it was more a
means of being attracted into areas I might not otherwise have
entered.

Any "conquests" have been purely personal. A long, hard day
in the hills has been pleasurable for the hours spent in wild
scenery and possibly wilder weather with CMC members, people I've
felt comfortable with, whose judgement I trust and respect in
difficult situations, and with whom I've relaxed later over a
pint. My rock climbing, by today's standards, has been extremely
humble although in the early days, women climbers were still very
much in the minority and I've received a fair dose of leg pulling
and many strange remarks. I've led the odd VS and a few Severes
but most of the time I've seconded. However, the highlights, to
me, have been days such as the one on Dinas Mot, when I stood at
the foot of  Direct Route , my first long Welsh VS, and shivered in
terror as I watched an International Party of climbers ready for
their ascents on various routes. They all seemed to know what
they were about. They were all clad in smart stretchy clothes and
had chalk bags and confidence and I was still behind the times
with thick breeches and sweaty hands. However, once my feet left
terra firma all fear disappeared and on the last pitch I belayed,
sat in the sun and chatted to other CMC members on a nearby
route, content that I'd climbed the route well and enjoyed every
moment.

My participation as a member of the CMC has, as for many
others no doubt, altered over the years. In the early days of the
Club I thrived on doing anything "en masse". Climbing was rarely
a quiet affair between leader and second, but more an invasion of
one climb by as many people as possible. I remember vividly
 Browns Eliminate  on Froggatt being peppered with struggling
bodies  mine being one , all being top roped at the same time. It
became like a child's puzzle, trying to trace back the rope to
"which leader?" We even drove in convoy on away meets to
Scotland! Safety in numbers? Would the natives attack us? Over
the years I became more solitary and anti social in my forays
into the hills, although I still enjoyed the getting together
with Club members at the end of the day. And now   well, not much
chance of joining club meets very often from this distance, but I
do have fantastic memories of past ones.

I would have liked to think that my five year old son
Alisdair would have been able to grow up with the CMC. Alan and I
took him onto Curbar Edge the very day he came out of the
hospital where he was born and I said to him:

	"This is air, these are rocks and that lump over there is
Win Hill, I hope you'll learn to love 'em!"

We had taken him on several Club meets before, sadly, we had
to leave the Sheffield area. However, those first impressions
appear to have stuck and he is now knowledgeable on nature and
accepts walking and the hills as a normal part of life.

Over the years, through the CMC, I've made some very good
friends and now one of the greatest pleasures for Alan, Alisdair
and myself is to welcome those friends here to Norway to enjoy
our fantastic scenery and the many varied outdoor activities.
Plus sharing a lot of nostalgia over the duty frees they bring!

Well, as I said at the beginning, my last visit to the
clubroom was almost two years ago. There were many new faces but
the atmosphere of a thriving and friendly CMC has little changed.
I hope that all newer members and older ones alike can look back,
like me, after twenty years of CMC membership and enjoy as many
wonderful memories and as many good friends.
