:SETUP:
#+TITLE:
#+AUTHOR: Ian Barton.
#+TODO: TODO(t) DONE(@/!) STARTED(@/!) CANCELED(@/!)
#+STARTUP: content indent
#+DATE: [2015-12-03 Thu 15:51]
:END:
The objective of this project is to re-publish the book that the
Castle Mountaineering Club produced in 1988 to celebrate it's 21st
anniversary in PDF and mobi format. This is intended to be part of the
Club's 50th anniversary celebrations in 2017.

The contributions for the book were originally written using
WordPerfect and published by Sheaf Press in Sheffield. The text has
been taken from the final draft , which was submitted to the
publisher. The original WordPerfect files have been added to the
repository for anyone who wants to see them. The photographs have all
been scanned from a copy of the book.

I am using Emacs [[http://org-mode.org][org-mode]] to edit the files. All the article files
are in plain text, making it easy for other people to re-use them. I
ma using org-mode to export the project in both [[http://latex-project.org/][LaTeX]] (to produce pdf)
and html (to produce mobi).

There are currently three git branches:

- LaTex: the development branch for creating pdf files.
- ePub: the development branch for outputting html which can be
  converted into ePub or mobi files.
- master: eventually both the LaTex and ePub branches will be merged
  into master, so books in all supported formats can be created from a
  single source.

Almost all of the development takes place in the LaTex and mobi branches.

It should be possible to create the book in all the supported formats
from the .tex and .html files.

* Never Mind the Geek Stuff, I Just Want to Read the Book.

The pdf version is available as [[https://drive.google.com/file/d/0B5zS0RKOunXLRmttSXFUc25SODA/view?usp=sharing]] . This is very much a
work in progress and is regenerated every time the project is
updated. At the moment I am just working on the first few chapters so
I can finalize the details of the layout and insertion of the figures.

For anyone who understands LaTeX you can edit the [[https://github.com/thecastle/thecastle/blob/master/org_files/TheCastle.tex][TheCastle.tex]] file
to alter the appearance of the final document. I have chosen to use
[[http://robjhyndman.com/hyndsight/xelatex/][XeLateX]] to generate the pdf file because it has better font handling
than pdfLaTeX.

There is a very preliminary version of the ePub book at: Text and
pictures are all there. However, the
formatting needs a lot of work!

Ian Barton.

** [2017-08-02 Wed] Fix Some Problems with Web Version.
Theme updated by upstream leading to various breakages. Most now
fixed, but page list CSS needs some work.
** [2017-06-30 Fri] Preliminary ePub File
This is still experimental. The text and pictures are all there, but
ti needs a decent stylesheet to make it look good. I should also be
able to convert it to a .mobi file, which will be readable on the Kindle.
** [2017-06-30 Fri] Several bug fixes.
I think that all the pictures are now in the correct orientation. In
the original book several photos were in landscape format, but this
doesn't look right on a screen, so all photos are now in portrait
mode.

I have fixed several errors in text formatting, particularly chapeters
with verse and lots of quotations. It's not 100% perfect, but I am
getting there!

I think that I have managed to convert all quotation marks to "smart"
quotes ie opening and closing quotes are now shown correctly.

The one big task left is to correctly italicise the ext as per the
original book. The conversion from WordPerfect  didn't carry over the
italics formatting, so I am going through page by page to fix this.

** [2016-09-14 Wed] Work Started on the Web Version.
You can see the web version at [[http://thecastle.github.io/thecastle][The Castle]]. This is in the early stages
of development, so expect things to be broken/changed. However, you
should be able to browse all the articles and photos from the original book.
** [2016-06-29 Wed] Update.
I have imported all the text, photos and cartoons. There seem to be
problems downloading the pdf from Github, so the download link now
points to Google Drive.

I have chosen to format the book as A5, as this was the way it was
originally published. The current pdf should look more or less like
the original paper version. There is quite a bit of work to do on
getting the photos/cartoons to mimic the original layout
properly. Also I need to proof read the text and fix things like quote
and italics.

If you find any problems you can either create an Issue on Github (I
think you need to create an account to do this) or  [[mailto:ian@manor-farm.org.][email]] me.

* About The Castle Mountaineering Club.
For more information about the Club please visit the [[http://castlemountaineering.com/][Castle
Mountaineering Club]] website.

* Feedback.
Probably the best method of providing feedback is to create a new
[[https://github.com/issues][issue]] on the Github website. I don't think you need to create an
account on Github to create an issue. Alternatively you can email me
at ian@wilkesley.net.

* Did We Miss Something Out of the Original Book?
If you have some new articles that you would like to be included in
the book, please email them to me and I'll add them as an addendum
Please note all contributions should be in plain text only!

After discussing this with Andy Smith, we have decided to keep to the
content of  the original book and not to add any initial content.
* The Todo List.

** STARTED Optimize photo and graphic layout.
:PROPERTIES:
:LOG_INTO_DRAWER: t
 :END:
 :LOGBOOK:
 - State "STARTED"    from "TODO"       [2017-06-30 Fri 15:16] \\
   Mostly done. Just need the check I haven't missed anything.
:END:

** TODO Fix Title appearing twice in Web pages.
HTML export always exports #+TITLE, which is the same as the H1 for
the article.
** TODO Edit articles to re-instate italics that didn't come over the the WordPerfect conversion.
:PROPERTIES:
:LOG_INTO_DRAWER: t
 :END:
:LOGBOOK:
:END:

** DONE Smart quotes.
:PROPERTIES:
:LOG_INTO_DRAWER: t
 :END:
:LOGBOOK:
- State "DONE"       from "STARTED"    [2017-08-02 Wed 12:10] \\
  Smart quotes should now work.
- State "STARTED"    from "TODO"       [2017-06-30 Fri 15:16] \\
  I think this is complete, but need to check.
:END:

** TODO Choose a decent font .

** TODO Fix Table of Contents so it looks better.
:PROPERTIES:
:LOG_INTO_DRAWER: t
 :END:
** TODO Sort out frontmatter (intro, etc), backmatter and appendix.
:PROPERTIES:
:LOG_INTO_DRAWER: t
 :END:
** TODO Create build script.
:PROPERTIES:
:LOG_INTO_DRAWER: t
 :END:

Should allow anyone with a vanilla copy of Emacs to regenerate the Tex
and pdf files.

** STARTED Start work on creating a Kindle book.
:PROPERTIES:
:LOG_INTO_DRAWER: t
 :END:
:LOGBOOK:
- State "STARTED"    from "TODO"       [2017-08-02 Wed 12:11] \\
  Very beta version of ePub fie.
:END:
** STARTED Upload images.
:PROPERTIES:
:LOG_INTO_DRAWER: t
 :END:
:LOGBOOK:
- State "STARTED"    from "TODO"       [2017-06-30 Fri 15:20] \\
  Uploaded, but need to check that I haven't missed any.
:END:
** TODO Italics!
:PROPERTIES:
:LOG_INTO_DRAWER: t
 :END:
** STARTED Create ePub version of the book.
:PROPERTIES:
:LOG_INTO_DRAWER: t
 :END:
:LOGBOOK:
- State "STARTED"    from "TODO"       [2017-06-30 Fri 15:18] \\
  Exported to ePub OK, but need to create a decent stylesheet.
:END:
