#+SETUPFILE: ./setup.org
#+TITLE: Rumble Groove.

* Rumble Groove
#+latex: \chapterauthor{Marian Birkett}

What do I remember about The Castle? Well it's people, days
out climbing, for instance days with Dave, well known for his
enthusiasm for climbing anything, anytime   although preferably a
traditional route on Kinder. If it's a vegetated chimney and it's
just starting to rain, well that's approaching Nirvana. The ideal
route description might be, "Climb straight up for 200 feet with
much botanical interest  a fine ten foot chimney then leads to
the top. First ascent 1892."

One day Rosie, Dave and I headed for a Peak District
equivalent: short, insignificant and green, on some boulders
which think they're a crag. Yes, the  in famous  Rumble Groove  on
Carl Wark. Not heard of the route? You're doing well if you've
heard of the crag!

Dave and Rosie had though, in fact it was Dave's third
attempt at this route. He had spent several hours pitting his
strength and skill, definitely in that order, against the rock
 it's that sort of route , retreating with bruised arms, legs,
ego, everything. Today would be different.

We approached the crag. Crag, did I say? I noticed some
rocks huddled together.
"That's Carl Wark," said Dave. " Rumble Groove  is well over
to the left there."
"Oh, really?"
"It's super. A real classic."

I tried to sound enthusiastic but failed miserably. We
uncoiled 150 feet of rope, 130 feet of which was totally
unnecessary. Peak District climbing is like that: crags that are
too short, ropes that are too long and, as we were to find out,
cracks that are too wide.

Dave tied on and Rosie belayed, so I was free to escape from
the midges and to wander about looking at the groove from
different angles   none of them in the least encouraging. I
hadn't seen Rosie for a while and we chatted whilst Dave grunted.
After half an hour we'd caught up on all the news  after an hour
we were dragging up insignificant crumbs of gossip.

Dave was struggling. First there's a wide crack leading up
left. The jams are painful, insecure, slimy and the crack
overhangs slightly: a gritstone climber's paradise! Standing on a
rock at the foot of the crack starts you off. Then you must lurch
onto the holds on the left  slight indentations in the vertical
rock  and power your way up the green crack.

The first runner is quite low, only useful if you fall off
the first nine inches of climbing and have an attentive second. A
number forty two hex would have been helpful higher up but Dave
had left it at home. I suggested wedging two hexes together or
passing up a large stone to jam in the crack  I thought the
latter might appeal to his traditional inclinations. But he'd had
enough.

He'd lost count of his attempts to get off the ground and
offered me the rope. Now I can't resist a challenge and certainly
this was one. However, I am a coward and my first priority is
always to get a runner above my head   well, even one a bit
higher than the last would help. Somehow, to hurt yourself
falling off a "Classic Rock" route on Cloggy or Gimmer might be
acceptable, but to fall off a boulder near Carl Wark, well the
indignity  of it all.

So with much ingenuity and a lowering of ethical standards
 this was a traditional route after all  I slammed a Friend in as
high as I could. This superhuman effort reduced me to a quivering
jelly, wobbling back next to Rosie. I quickly returned the rope
to Dave after Rosie had refused it   she's got more sense!
With the confidence of another runner and fresh from a good
rest, Dave attacked the rock with daring spirit. We gave him lots
of encouragement by pointing out that we had only five minutes
left before we were off home and suddenly, to our great surprise
and consternation, he was cheering from the top. Oh no! That
meant that we'd have to do it.

I went next. After an interminable fight in the crack,
leaving it dripping with blood, I emerged secretly vowing never
to let Dave pick the route again. Rosie went next, the fastest
ascent yet.

Our attention was then drawn to the only other route on
these boulders,  Green Crack . A similarly attractive climb, its
name being most descriptive  a green, slimy, rounded crack. They
gave me the rope and, teetering and complaining, I reached the
top. I was surprised when they declared it twice as nasty as
 Rumble Groove . So if you're wanting to reduce someone's
enthusiasm for grit, I thoroughly recommend a day out somewhere
near Carl Wark. As for climbing with Dave... you have been
warned!
