:SETUP:
#+SETUPFILE: ./setup.org
#+TITLE: Ridge Routes in the Land of The Rising Sun.
:END:

* Ridge Routes in the Land of The Rising Sun
#+latex: \chapterauthor{Dave Kime}

This area had long been neglected by the Club, although
older members could recall long days spent hacking through ivy on
exposed ridges and ascents of swaying trees. Spurred on by these
legends and by reports that chunks of stone were falling off some
of the routes, the Club held several meets in this area so close
and so unfamiliar to most Club members   the clubroom roof.
These meets were inaugurated by Sean, who unfortunately was
unable to ensure good weather. The first one was cancelled by an
eighteen inch snowfall and the second gave us a wonderful
experience of what it would be like to install a window in the
middle of Kinder Downfall. We had a chance to look at the roof
only very briefly while Andy indulged in the legendary pastime of
ivy clipping. We were by now a little more aware of the problems
we had to tackle and the committee set aside three further
Saturdays for the purpose.

Our next meet was somewhat exploratory but we found a number
of loose slates and a decaying chimney on the outside. Andy,
Charles and Frank constructed a spider's web between trees,
telegraph poles and the chimney stack and set about
reconstruction, whilst Dave and Tom prepared Ready Mix, filled
the gaping holes under the eaves and did some pointing. A
successful day, marred only by the sight of a forlorn starling
looking for the entrance to its nest next to the chimney stack.
The major problem then remaining was how best to stop the
mortar falling off the inside of the roof and annihilating the
members. We had many ideas but little real knowledge. However,
fate was kind and brought us a new member, Chris, who in a rash
moment admitted he was a builder and in an even rasher moment
volunteered to come on the next meet. Perhaps he had seen our new
chimney stack and realised that we were real craftsmen, or
perhaps he had seen the chimney stack and realised ...

Two weeks later we met again. The chimney was still standing
and Chris was very polite about our work but we hoped he wouldn't
look too closely. We were then shown how to use mortar trowels
and since this appeared so easy we got on with the job of
knocking down the eighteenth century mortar whilst Chris fixed
the slates on the roof with a total disregard for the ropes and
ladders with which we had festooned ourselves on the previous
meet. By lunch time the floor was deep in old mortar and we now
had to fill in the holes we had made. This was not as easy as
Chris had made out and a number of us resorted to mortar stuffing
by hand rather than by trowel. While Chris hung to the rafters by
his toe nails and mortared the higher reaches of the roof, Roger
swung from the planks and delivered well aimed dollops down the
neck of anyone who passed below. Andy swung across the walls on
an elaborate arrangement of slings and during his girdle traverse
of the clubroom demolished only two of the spotlights.

Mike and his son Mark joined us for the afternoon and while
Mike filled, Mark delivered pots of gunge to the inaccessible
corners of the clubroom. Disposal of the debris took quite some
time, as did the removal of Roger's wedges of mortar from our
spines. We had at least completed the work at the end of the
clubroom nearest the climbing wall which we now felt was a little
safer, even if the holds did require a dusting. A rather smaller
party met to deal with the remainder of the roof. With the
numbers available, we also managed to clear and re point two
sections above the upstairs room, which offered rather less of a
challenge than the previous week due to their accessibility.
Whenever we plan to work on  the roof, come along: it's great fun
and Your Club Needs You.

So, if you see a member in climbing gear with an ashen face
and a concrete helmet, he's probably just been climbing in the
Land of The Rising Sun.
