:SETUP:
#+SETUPFILE: ./setup.org
#+TITLE: Island Flings.
:END:

* Island Flings
#+latex: \chapterauthor{Mike Doyle}

Islands hold all sorts of fascinations although for some more than
others and for me more than most. The Castle Mountaineering Club has a
climbing interest in the Scottish Islands of Arran, Rhum and Skye and
these islands therefore feature frequently on the Club's summer meets
list. In my case, a keen interest in islands has become an obsessive
urge to visit ever remoter, wilder and far flung spots. I am, though,
wary of the D.H. Lawrence tale "The Man Who Loved Islands" in which
the subject of the story, seeking ever smaller island sanctuaries,
finally retreats to a slab of rock from which he is swept clean away.

My interest in islands began in Easter 1974 with a visit to Arran. The
trip involved leaving my then base of Reading at five o'clock on
Maundy Thursday evening, travelling to Bristol to collect one member
of the team and and then undertaking a further journey to Stoke on
Trent to collect two other members, followed by a run to Ardrossan and
the early morning ferry to Arran. The return was equally frantic and
saw me back at my desk at nine o'clock on Tuesday morning. In between,
however, was an experience of true island bliss blue skies, anti
cyclonic weather, a snow capped Cir Mhor and vistas of the west coast
of Scotland and the nearby Paps of Jura. It was a three day glimpse of
paradise that started a permanent island obsession.

Having whetted my appetite with the benign and accessible beauty of
Arran, I began looking for more demanding locations, preferably those
with mountaineering potential. A timely move to Sheffield and
subsequent membership of The Castle Mountaineering Club certainly
helped. Mull, Skye, Rhum and Jura became obvious
choices. Unfortunately, I arrived in Sheffield with too little time
spent in my new employment to have earned a week's holiday and
therefore felt obliged to remain south of the border whilst the Club
trip to Skye in May 1975 went ahead. That was the year Skye wilted
under a week long heatwave and much serious climbing was done
including a Club traverse of the Cuillin Ridge. All I could do was
seethe with rage on learning what a good trip I had missed.

The following winter I learned that the Club was planning a Spring
Bank Holiday meet on Rhum, but I was again unable to join the
trip. Rather than miss out altogether, I obtained permission to camp
on the Island at Easter and so got there in advance of the main Club
expedition. I shall never forget the feeling of commitment at the
sight of MacBrayne's ferry steaming away, leaving us ashore with only
the tents and the food we had taken to sustain us for the coming
week. A week of gales, leaking tents and wet sleeping bags took away
some of the initial gloss, but the experience of watching deer only
feet from our tent and an ascent of Askival on the only day of
brilliant sunshine with views of the Cuillin on Skye, the nearby Small
Isles and more distant Outer Hebrides shimmering beyond the deep blue
Minch, easily compensated for the grimmer times. I was, though, left
with a slight "niggle" when the subsequent Club trip in the Spring
again found good weather and members packed in the routes.

The Rhum experience led me to visit a series of small and remote
islands where the attraction was the intrinsic interest of the island
itself rather than any mountaineering opportunities.  Thus it was that
I arrived green and seasick in North Haven on Fair Isle after two
hours tossing about on the sea on the Island's mail boat. Ignoring the
obvious mountaineering and swimming!  challenge of Sheep Rock, I was
enchanted by the peace, abundant wildlife and cheerful simplicity of
the fifty or so human inhabitants.

Thoroughly "hooked" by now, I spent a fortnight ploughing the
Hebridean waters helping as crew on a seven berth yacht.  Twice it was
nearly all ended: first by a scrape with an unexpected overhead power
cable on the west coast of Lewis and secondly by a navigational
blunder that led us late at night into an uncharted bay at the
entrance to Stornoway harbour.

Through this island touring, I eventually developed an obsessive
interest in a small, remote and hard to get to island group beyond the
Outer Hebrides. I mean of course "The Islands on the Edge of the
World" as they were once described, or St Kilda by their present
name. I first noted them with little more than idle curiosity as dots
on the map, but then I read an article in a climbing magazine which
aroused my interest. The description of the highest sea cliff in
Britain and the largest gannetry in the world, surrounded by Atlantic
seas, drew me to these islands like a magnet. The sad story of the
former occupants of the islands, their fate at the hands of
"civilization" and their ultimate evacuation added human interest.

However, my attempts at getting there were singularly
unsuccessful. Twice The National Trust for Scotland rejected me as an
applicant to join a work party, and an attempt to sail there by yacht
had to be abandoned in high seas. The more my attempts to get there
failed, the more I became obsessed with these Islands and the more I
redoubled my efforts to find a way to cross that elusive forty five
miles of Atlantic Ocean.

Eventually my patience and perseverance triumphed and I did duly set
foot on the shore of Village Bay on Hirta, the main Island. Here at
last was a remote island, well out to sea, out of sight of land and a
truly wild place. The teeming sea bird life was ever present, the wind
and sea pervaded all nooks and crannies and the drama of the cliffs
was mind blowing. Yet amidst all this drama the old village and the
old graveyard peacefully enhanced the natural appeal of the southern
sweep down to the sea of the Island's highest point, Conachair.

It was with a heavy heart that I bade farewell to these lonely and
spectacular islands and returned to mainland Scotland.  There have of
course been other islands since and I have more targets for the future
for example Foula, reputedly the St.  Kilda of the Shetlands. Perhaps,
though, I should try further afield. A glance at the shattered
coastline of Norway also looks promising, with gems like the Lofotens
very appealing and rekindling the old mountaineering spirit. Yet the
lure of the Scottish Isles is hard to shrug off and once again I shall
find myself setting off to the Hebrides. Although I shall be
trespassing rather close to the Corrievrecken whirlpool, there are
hopefully sufficient reasonably sized islands around to avoid my
resorting to slabs of rock and experiencing the watery grave warned of
by Lawrence!
