:SETUP:
#+SETUPFILE: ./setup.org
#+TITLE:
:END:

The Castle book was originally conceived as part of the Club's 25th
Anniversary celebrations in 1988. I well remember long nights of
editorial discussion over the placement of a comma and the finer
points of English grammar!

A great many things have happened in the intervening 12 years. I no
longer live close to Sheffield (although I am closer to Wales). I can
no longer climb regularly as we now have two young children (John,
aged two and Ella aged six months). However, John is showing some
interest in climbing ("Daddy go up big steps.") and we visit the hills
regularly.

I don't imagine it will be too long before I am once again dossing
under Cromlech boulders, with two small companions. John is already
assimilating the finer points of climbing - "Daddy have beer, Mummy
have cider, John have fish fingers and chips." He has already has his
introduction to that centre of climbing culinary delight - Pete's
Eats. I hope it won't be too long before we can come out on a family
meet.

The advent of the Internet has made it possible to reach a much wider
audience. By publishing the book on the Internet I hope that Club
members who have moved to distant corners of the world can be reminded
about the Club's exploits. The articles from the book also provide a
good read for anyone interested in mountaineeering and will maybe
encourage a few new people to come along to the Castle Club.

Ian Barton.
