:SETUP:
#+DRAWERS: SETUP NOTES PROPERTIES
#+TITLE: The Founding of the Club.  by Mike Anderson
#+OPTIONS: num:nil tags:nil todo:nil H:2 toc:nil
#+STARTUP: content indent
:END:

* The Founding of the Club.  by Mike Anderson

Langdale, 29th September 1967: torrential rain, the road flooded in
several places, the campsite very much the same. Hardly an auspicious
first meet for a new Club, but one that is nevertheless still
flourishing twenty one years later. All members of the Club have since
experienced similar discomforts, with the additional attractions of
cold, hail, sleet and snow. Now at last we can reveal where the
responsibility lies.

Alec Barclay came from across the Border to seek satisfaction for
causes long gone: at least that is what we put it down to when we were
induced to go to Scotland and elsewhere to be tortured by long walks
and hard climbs. Alec and his colleague Colin Mackie had first taken a
small party of Sheffielders for a weekend in Glencoe in March 1967,
followed by a further visit in July the same year. It was after these
trips that the idea of forming a club came to Alec. Discussions back
in Sheffield met with enthusiasm and convinced Alec that he had the
nucleus for the formation of a viable club.

A nine strong meeting of stalwarts held at Ashley and Avril Turner's
house on Monday 25th September 1967 led directly to the founding of
the Club. As all of them were "regulars" at The Castle Inn at Bradway
it was natural and appropriate as they intended to meet there on their
weekly club night that the Inn should lend its name to the Club. But
what to call it? The Castle Climbing Club, or The Castle
Mountaineering Club? After a long discussion it was decided to name it
"The Castle Mountaineering Club", in the belief that this title
indicating the basic principle of putting one foot in front of the
other to gain height would provide the widest possible base for the
Club and give encouragement to prospective new members.

A proposal by Alec that the Club should exist to further the spirit of
mountaineering on the one hand and to offer instruction in specific
techniques on the other, was duly accepted. It was agreed that The
Castle Inn should be the Club's headquarters until suitable premises
could be found. Alec himself would act as first Hon. Secretary and
Colin Mackie as first President, a , committee was duly elected and a
constitution adopted on 9th October 1967.

The success of The Castle Mountaineering Club owes a great deal to the
decision taken in those early days to establish the Club as a
"Mountaineering Club". Members have been encouraged over the years to
extend their mountaineering skills over a wide range of activities, be
they climbing, hill walking, skiing or pot holing even pot holing: a
little difficult to put one foot in front of the other underground and
still gain height! Whatever the activity, the Club has always afforded
opportunities for its members to acquire experience in all aspects of
climbing and mountaineering.

Regular meets were held from the outset with climbing sessions every
week on local Edges and an away meet each month to different parts of
England, Wales and Scotland. The Club rapidly became something of a
family with meetings in members' houses and with slide shows and
lectures in addition to the regular club nights at The Castle Inn.

THE FIRST STEPS HAD BEEN SUCCESSFULLY TAKEN.

But with growing membership, the need to find a clubroom which would
fulfil one of The Castle's ambitions soon became apparent. That saga,
an epic in its own right, was about to begin.
