:SETUP:
#+SETUPFILE: ./setup.org
#+TITLE: Cairngorm Plateau Traverse.
:END:

* Cairngorm Plateau Traverse

by

Mike Jackson


An annual highlight in the early days of the CMC was the
winter visit to the Cairngorms. For many members this was their
first experience of the magnificent snowscapes and near arctic
conditions to be enjoyed  or endured  in Scotland during the
winter months. A particular outing on these hills in February
1970 proved to be one  of the outstanding days of an early CMC
Cairngorm Meet and at the same time illustrates very well the
conditions one may reasonably expect to meet in winter in the
Highlands. Our party consisted of Mike Anderson, Jack Ashcroft,
Chris Taylor, Paul Goodlad, Dick Arnold and myself and our
objective was to traverse the great plateau from Cairngorm to Ben
Macdui and back.

The early morning was beautifully clear under a blue sky and
with deep snow everywhere. I regret to record that certain
members were aided in varying degrees by the chairlift in their
initial ascent of Cairngorm. I myself had to endure an
uncomfortable "stitch" but the glorious views were ample
compensation. As we descended to the west from the summit, we
could pick out a column of walkers on the plateau below,
resembling a trail of ants and giving a wonderful sense of scale
to the scene. The vista ahead of Cairn Toul, Braeriach and Sgoran
Dubh Mor was particularly splendid and there was a magnificent
view across to Fiacaill Ridge and the neighbouring cliffs
plastered in brilliant white snow with huge cornices. The going
was fairly arduous as the snow was not sufficiently frozen to
take our weight and we were constantly sinking in up to our knees
and beyond. We made our way to the Corran Bothy near Feith Buidhe
 a bothy later demolished following a tragedy hereabouts when a
number of children perished in the snows  only to find it
completely covered by snowdrifts except for the yellow chimney
cowl which stuck out grotesquely from the snow. There was a
really breathtaking view across to Braeriach with its great
coires gouged out of the plateau, all completely snow covered
under a cloudless pale blue sky. The summit of Ben Macdui gave
further wonderful views, particularly across to Cairn Toul and
the peaks beyond it, down to Carn a'Mhaim and the great snow
filled trench of the Dee and far away to Beinn a'Ghlo well to the
south. The Devil's Point, a spectacular peak when seen from the
Lairig Ghru track coming in from the south, appeared far below
our elevated position as a minor protuberance in this great
winter landscape.

It was then that my personal troubles really started as I
became very ill and had to retire urgently behind snow covered
boulders. The "stitch" which had afflicted me most of the way to
Macdui suddenly became much worse and on the return journey it
was impossible for me to walk any distance without stopping for
breath. To make matters worse, the wind began to increase and
great black clouds were approaching from the north west. The
weather closed in rapidly and the spindrift, combined with
falling snow in the mist, soon created near "white out"
conditions. Before long I was reduced to walking a few yards at a
time and later on I was able to think only as far as the next
step in the deep snow. Most of the party had gone ahead but
fortunately for me, Paul and Dick stayed behind and were able to
give much needed assistance. I had never before felt so weak and
ill on any mountain trip and I was deeply and genuinely grateful
to my good friends for their assistance  without them, my
predicament would have been very serious indeed. The last small
ascent to the top of Fiacaill a'Choire Chais seemed never ending,
but we could at last descend the ridge, suddenly emerging from
the mist and snow to look down on a hive of activity on the ski
slopes below. Within a few yards the howling winds and generally
adverse conditions on the plateau had been left behind and  after
descending only a few hundred feet it was impossible to imagine
the violence of the wind and lashing snow which had made our
return so difficult. It remained only for us to stagger down to
the ski lift and safety.

 All walkers undertaking this traverse would do well to bear
in mind the remoteness of Ben Macdui  even in these days of
chairlifts on Cairngorm  and the sudden changes of weather often
experienced in these great hills. I have never forgotten the
great contrast between our glorious sunny walk to Ben Macdui in
such wonderfully clear conditions and that return journey on
which my personal discomforts and the adverse weather conditions
combined to create a real nightmare. The views we had enjoyed
throughout the morning of these great snow covered mountains had
been outstanding under a clear winter blue sky, but the day ended
with gales, spindrift, dense mist and snowfall   a combination of
the elements among the most difficult and dangerous we learn to
face on our beautiful yet challenging mountains.
