:SETUP:
#+SETUPFILE: ./setup.org
#+TITLE: Pillow on Pillar.
:END:

* Pillow on Pillar

by

Mary Peace


Big Al had forgotten to bring the tent and we would have to
collect it on the way although this meant travelling fifteen
miles in the wrong direction. As we managed to miss the correct
turn off the motorway we did in fact travel thirty unnecessary
miles on the southbound carriageway  before we finally headed
north, my ruffled equilibrium soothed by a generous helping of
Alan's smooth, mellow whisky. We arrived eventually at Wasdale,
quickly donning duvets against the cool October air, and helped
Pat to pitch the tent by torchlight. I snuggled down thankfully
into my sleeping bag.

6.00 am - Feet thundered past the tent and I popped my head
out to see Big Al's figure disappearing across the field. Some
members of our party were already on the move. The remaining six
of us emerged rather more slowly and it was a considerable time
later that we started up Black Sail Pass.

Arriving at the col, we took the climbers' traverse across
the shattered northern slopes of the mountain - our destination
Pillar Rock. By 2.00 pm we were at the foot of    New West   , our
chosen route, ready to climb. The rock reared up magnificently
for 300 feet above a fearsome gully. I was impressed! It was very
intimidating. Frankly, I was petrified. It was our very first
long climb.

Our friends  the early risers   were already half way up
their climb by this time. We watched them as we ate our
sandwiches. By the time we were half way up our route, they were
back at the foot of    New West   . They watched us until Pat, who was
leading our rope of three, emerged at the top of the last and
most difficult-looking pitch on the climb  then Big Al shouted
up:

"You got a bit off route there, Pat. You've just finished
the crux pitch of    Sodom   ! And you haven't finished when you reach
the top. It's quite a climb to get back down again."

"You'll be alright" he added. "You've got a rope!" and they
set off back over the Pass to the comforts of the campsite and
the Wasdale Head Hotel.

Sodom was VS. We were supposed to be climbing a V Diff! I
was very much aware both of the fearsome gully 250 feet below and
the impossible-looking pitch above. The fear which tingled
through my veins was for me an entirely new experience.

There was hardly room to move on the tiny stance I was now
sharing with Dick. Older and even less experienced than Pat and
I, Dick was all sinew and guts - motivated completely by
willpower.

"Try standing on my shoulder, Mary" he said.

With this difficult manoeuvre accomplished, I managed to
launch myself into that strenuous VS chimney. My battles with the
capping chock-stone are better not dwelt upon but eventually, and
very thankfully, I found myself up there, actually on top of
Pillar Rock.

 What a magnificent place to be! About a quarter of an acre
of rough rock to scramble over, surrounded on all sides by
precipices. Lakeland peaks lay all around us and Ennerdale,
filled with forestry-planted pine trees, stretched from the foot
of our mountain as far as the eye could see. But by now the pale
October sun was looking very low in the sky.

5.00 pm in October.

"How the hell do we get off this Rock?"

Dick and I walked round and round the perimeter looking for
possibilities, whilst Pat manned the top of    New West     or was it
   Sodom   ?  ready to make contact with and offer help to those still
below.It began to feel like evening.

Six members of another party arrived on top, having climbed
up various routes. No-one knew the way down! Eventually,  the
leader of the other party discovered a route he could reverse. He
threw down a rope and proceeded to see his party off. Just as he
said "Good Luck" to me and disappeared over the edge, our last
climber arrived at top of    New West   . Dusk. Lots of rope to
control!

"Sorry - we must keep moving. We've got to get off this damn
Rock."

When we reached the bottom it was dark  by the time we
reached our sacks it was pitch black. Pat's torch  he was the
only person who had one!  enabled us to cross that frightful
gully and traverse just a little way before reaching a tiny
grassy shelf, where we decided it would be prudent to stop.  -
10.30 pm   All clothing donned but no clothing census taken
- a mistake that. Four of the party were lying close together on
a single exposure blanket. Pat and I occupied our only exposure
bag.

Lights. Down there in the Ennerdale valley. Flashing lights
and shouting - but who? We flashed back. Soon they went away
again. They won't come up to get us until morning, I thought,
perhaps the others were managing to get some sleep. Everyone kept
quiet   another mistake, that.

I remember Pillar Rock looming in the darkness, quite near
to us. It was like being surrounded by black velvet, not a
flicker of light anywhere, just a vague paler shade of black in
the sky over Scarth Gap. I remember the plastic of the exposure
bag flapping round my face in the strong gusts of wind  I
remember being aware that we had slipped a little way down
towards the edge of our grassy shelf where the mountain dropped
away into the darkness  and I remember everyone suddenly becoming
alert and aware as the lights of vehicles appeared down below,
streaming up the Ennerdale valley and coming to a halt at the end
of the road. We could hear a dog barking. Six little lights
formed a crocodile and started up the mountain. Cockermouth
Rescue Team had arrived.

Our party now stirred itself. Two different members of the
party took their turn in the exposure bag and we wrapped up a
third in the blanket. It was at that point we discovered he was
only wearing jeans! We nibbled Turkish Delight as we watched
those torchlights moving up the mountain. I will never forget
that sight, or the magnificent men who reached us some forty
minutes later  the hot sweet milkless tea they gave us  what
nectar! , the clothing, the bars of chocolate, the big alsatian
dog and their radio call sign:  "Poppopoppoff".

"Okay, we've found all six of them. No-one hurt. Over."

We each had a personal escort down, in spite of which Pat
had a rather nasty fall. Near the bottom of the mountain the
Warden from Black Sail Youth Hostel was waiting and as we walked
the last half mile to the Hostel it started to rain. Eventually
we found ourselves sipping hot soup in the Hostel and enjoying
the friendly hospitality which the Warden provided. We were very
glad not to be still out there on the mountain.

We had hardly finished breakfast next morning when our CMC
escort arrived to see us safely back over the mountain pass to a
reunion with our friends at Wasdale. Not abandoned to our fate
after all!
