:SETUP:
#+SETUPFILE: ./setup.org
#+TITLE:
#+TITLE: The Castle Wall.
:END:

* The Castle Wall

by

Steve France

Indoor climbing walls have long provided both amusement and bemusement
to climbers and spectators alike. The Castle climbing creation is no
different in that respect but, due to its unique location in the
clubroom, its frequency of use tends to reflect certain phases of
interest within the Club. An increase in the wall's popularity usually
occurs at times when there is an influx of new members or novices, or
when there is a strong climbing contingency.

The climbing wall's construction and development in the early
seventies paved the way for the sudden burst of interest it received
between 1978 and 1981.  This was chiefly due to the production of the
first ever guide book to the outcrop and a large enthusiastic group of
climbing members. Competition within the Club reached a peak in 1980
and this is reflected by the new routes section in the back of the
guide book, a good example being the route called The Merry Monk .
This hotly denounced route was climbed by Tom Benson with the use of a
hold that was allegedly out of bounds half an inch to the right! . It
was quickly climbed without the use of the offending hold by Steve
France who renamed it Short Black Curly Hair but the arguments did not
end there due to mounting ethical disagreements. Both Tom himself and
Richard Staniforth who also attempted to "take the glory" were over
six feet tall and could easily reach past the crux move - much to the
annoyance of Steve who could not do it without making a ridiculously
hard move. Despite several weeks of contemptuous lip the true claimant
to the fourteen inches of newly climbed rock was never decided - but
who cares anyway?

Steve Hartland, as a reflection of the times, promptly free climbed
all the aid routes, and for entertainment Keith Naylor thrust his
person onto the rock to create Lunge or Plunge . The route should
really have been named Lunge and Plunge, since it allowed a means
of reaching the top using only two footholds and one hand hold. If
you think that sounds amazing then ponder over the fact that The
Crack was climbed from top to bottom using only one hand jam. You
are advised not to attempt this unless you are proficient at
mid-air jamming!

The Club supplies various items of equipment for members or visitors
wishing to climb on the wall, including ropes, helmets, and various
old pairs of rock boots. It is always stressed that climbing is at
one's own risk and that utmost care is required.

The Castle must be one of the few clubs to have its own climbing
wall - so why not give it a go?

Please Note.... all routes graded over HVS can only be climbed wearing
lurid coloured tights and headband. Please also remember that the use
of chalk is forbidden!

Good Luck.
