* Rhinogs Meet
by
Frank Mellor

Arriving at Dinas Farm in the early evening of Friday I was
surprised to see Sean, Mel and family already prospecting for a
good pitch. We had pinched an extra day to climb on Tryfan and
although we had stopped in Beddgelert for a beer with Dunk, I had
expected to be first at the campsite.

"Evening Sean, not been hanging about then?"
"No, we got off early and had a good run down. Had a good
day?"
"Aye, we've done  Grooved Arete . Bit nippy on the fingers but
a great route. Nobody else here?"
"Not seen anybody yet. Nice spot this. I think we'll get
settled and put a brew on."
"OK Traverse tomorrow? Weather looks promising."
I put up our tent a fair distance from Sean's as I wasn't
certain how young Pete would react to his first night under
canvas. After lamb chops it was nearly dark  after discussing
transport arrangements it  was  completely dark  and after drifting
off to sleep for five minutes it was light again! Car headlights
illuminated the canvas. Dave and Jenny with Andy and Rosy.
"Hey Frank, doing the Traverse tomorrow?" Andy wanting to
get it sorted.
"Yep. Wake you up at six."
"Six? Bit early, in't it?"
"Yeh, but Sean's keen not to be late back and Mel's going to
come and pick us up."  Always blame somebody else!
"OK then."
Drift off back to sleep again. Ten minutes later   same
performance with Vanda. Anyway, now everybody knows.
Half past five, alarm goes off. Damn thing's somewhere under
the flysheet. By the time I've struggled with the zip it's
stopped ringing. Bash it one anyway. Start a brew and leave it to
Jennifer. Stick head out   lovely! Sun coming up and pale blue
sky. Over to Sean's tent and whisper   instant reply. Over to
Andy's   nothing. Try again but this time stick head round flap.
Now there's a bit of snorting and the bag starts to move.
Suddenly the top half of it rears up and out pops a bleary eyed
face.
"Andy. It's six o'clock."    "Yes I know. I was just waking up. You needn't have
bothered."
As if this isn't enough I get a withering glare from Rosy
out of the gloom at the back of the tent. I sure wouldn't like
this job every morning! Vanda's reasonably civil though and Colin
manages a muttered reply. That's everybody. Dave and Jenny are
doing a slightly different walk and, knowing them, they've
probably been gone an hour already.
Whilst having a cuppa outside the tent I hear the first
cuckoo of the year and a few minutes later a heron flaps over.
People are emerging, gathering rucksacks, pulling on boots,
sorting out gear. Should be ready for off soon. Wait a bit
where's Colin?
"Anybody seen Colin?"
Nobody has. The beggar's gone back to sleep. He's eventually
persuaded out and we're off in two cars round to Trawsfynydd.
We park just off the track up to Cefn Clawdd, at an old
quarry site. We're walking by 8.15 am. Not bad considering we'd
been aiming for 7.30! We go up over wet ground, finding and then
losing a track to join the ridge just east of Diffwys. It's warm
work and pullovers are soon shed. On Diffwys it's cooler.

Roughish going with detours for crags and deep rocky trenches on
the way to Ysgyfarnogod  Sofarso good . Now "The Celtic Badlands"
and Clip. Much cooler now and the strongish breeze is blowing
clouds of May blossom up from the valleys. Strange how its petals
melt when they touch the skin. Elevenses on Clip. Ratatouille for
Vanda, cheese butties for me. Craig Wion is tough going but the
weather is being kind. Snowdonia is getting it and we can see
fresh snow on the Arenigs, but we're in the clear apart from the
occasional flurry of blossom. I'd like to have a beer with Dunk.
The way is barred again by rock walls and trenches.

Profanities from unexpected sources accompany our passage. Only
the graffiti on the rock walls forces the realization that we've
made it to the Roman Steps. Lunch on the big Rhinog! Easily up
after an awkward first couple of hundred feet. Past Llyn Du and
into sunshine on the long shoulder leading to the summit. A small
group of backpackers is just leaving. A nice rest there. Quiche
Lorraine for Vanda, pasty and Guinness for me. I'd like to have
another beer with Dunk!

Those who've been here before assure us that we're
psychologically over half way and that there are paths over the
remaining ground. Ten minutes later we are hearing that there is
no reason why an apple shouldn't fall upwards from a tree.
It's    something to do with statistics. One thing's for certain. There's
a helluva dip between Rhinog Fawr and Rhinog Fach  it feels like
sea level in Bwlch Drws Ardudwy.

There's a difference of opinion at the Bwlch. Colin and
Vanda go up past Llyn Cwmhosan and the rest of us go straight up.
We give it some fettle and get there first. Colin's not long, but
arrives with the news that Vanda is missing this one out. We
catch her up just past the imposingly situated Llyn Hywel. Y
Llethr is the biggest hill of the day but doesn't feel it, the
going is better. There are grassy paths. Apples do fall upwards.
The pace quickens up to Diffwys. The evening sun delineates the
majestic north face of Cader Idris. What a tremendous walk! We're
dropping from the south west ridge of Diffwys to the col. Over
Craig y Grut to Bwlch y Rhiwgyr to Sylfaen, to Mel waiting with
the car and lastly to the fleshpots of Barmouth. Fish and chips,
beer at last with Dunk. The atmosphere is great!

As we sit drinking, the dreadful thought occurs to us that
the pub may be closed tomorrow  Sunday . We ask the landlord who
confirms our suspicions. Andy returns from the bar.

"It  is  dry tomorrow, Andy," says Rosy.
"Oh, have you heard the weather forecast then?" asks Dunk,
waking up...
Unfortunately it  is  wet. Steady rain that doesn't look like
stopping. Ian has arrived. We cheer him up by telling him what a
good day he missed yesterday.
It's a late start. Vanda's due back in Sheffield but the
rest of us drive to Barmouth and pay 12p for a walk across the
toll bridge. At the other side first Colin and then Dave decide
it is not worth it. Colin goes bird watching and Dave goes to dry
out, having discovered his anorak isn't waterproof. The dwindling
party plods on.

Jennifer insults Ian by telling him he'll be the next to go.
It works. He stays. We follow the disused railway along the south
side of the Mawddach estuary to Penmaenpool. The rain lashes our
backs.

Lunch in the shelter of the pub  it  is  closed . Over the
toll bridge to Borthwnog. Only 1p this time. The rain has stopped
but there is a strong drying wind.

Pleasantly up through the woods to Garth gell. A jay hops
across the path. A squirrel scampers ahead. We link paths and
forest tracks back towards Barmouth. It showers on and off. We
put anoraks on and take them off    and on and off.
We finish at Barmouth's Panorama Walk. A commanding view up
the estuary and out to sea. Cader's hidden behind the clag. Back
in town, Colin and Dunk are dozing in Dave and Jenny's car. We're
back and dry.

The evening passes by as meals are cooked, then there's
chatting outside the tents in the gathering gloom until it's too
cold for comfort.

Monday morning. Grey and unsettled. Tops look likely to be
cloudy. The Kimes suggest the Berwyns. No one objects, so it's
down tents and off to Llandrillo.

A pleasant spot this: a spired church and an elegant bridge
over a fast flowing river. A gentle path leads up onto the broad
ridge where we stop for a bit near the "Wayfarer" plaque. The
clouds have rolled away and although it's still overcast, there's
no rain. A strong breeze makes us don cags for the ridge up to
Cadair Bronwen. The long ridge rolls us on to Cadair Berwyn and
Moel Sych where we turn north west and head back over marshy
ground toward the valley. Lovely warm sunshine welcomes us back
to the village.
Our weekend in Wild Wales is over.
