:SETUP:
#+DRAWERS: SETUP NOTES PROPERTIES
#+TITLE: A Trek in the Andes
#+OPTIONS: num:nil tags:nil todo:nil H:2 toc:nil
#+STARTUP: content indent
:END:

* A Trek in the Andes
by
Bob Madeley

The Cordillera Blanca in the Peruvian Andes is one of the
most beautiful mountain ranges in the world, with peaks reaching
a height of more than 6000m. Although not as high as the great
giants of the Himalaya, these mountains hold second place to none
in shape and grandeur. It was with the prospect of experiencing
this grandeur that eleven of us, led by Alf Gregory  Greg , set
off from England with perhaps a little trepidation to this wild
area on the other side of the world.

After two days in the bustling city of Lima we left by bus
on the 250 mile journey to Huaraz, crossing part of the Atacama
desert through which passes the Pan American Highway. This is a
road cut through the sand and which in places reaches a height of
one hundred metres immediately above the sea. As we moved inland,
many roads had washed away by floods and rivers and the driver
was often forced to drive along dry, rocky, river beds until the
road could be regained.

After a very hot and dusty ten hour drive punctuated by
several breakdowns, the bus, with very suspect brakes, at last
reached Huarez. En route we had taken a short side trip to the
Parachota Valley on the edge of the High Cordillera. In this
remote valley of sparse vegetation and deep clear "coral like"
pools, we saw the Puya Raimondi which has the tallest flower
spike in the world, attaining a height of eight metres or more.
This plant is confined to the Peruvian and Bolivian Andes and may
live for one hundred years, flowering just once before it dies.
An estimated eight hundred flowers grow on one stalk, attracting
the humming birds which play a large part in their pollination.

A tortuous alpine style road led us above Caraz and the
first sight of a beautifully shaped peak of Santa Cruz got our
adrenalin flowing. The arrieros packed our gear onto thirty five
burros and along with a horse and three scraggy dogs we ascended
the steep gorge which, after three days travel, led us to the
Punta Union Pass  4,750m .

Continental drift, resisted by the Earth's crust below the
Pacific Ocean, has created intense compression and has crumbled
the land's surface, releasing the igneous rocks which form most
of the highest peaks. The effects of glaciation, volcanic action
and water erosion have completed the process and have helped to
form the sheer mountain sides above the deep gorges through which
we passed. The extreme temperatures between day and night, so
near to the equator, continually freeze and thaw the snow and
ice, forming beautiful jagged peaks with grotesque shapes along
the ridges.

Swamp areas, created by the lakes gradually drying out,
seriously impeded our progress yet revealed a vast variety of
beautiful plants and flowers, at their best in June, as we
splashed our way through the clinging bog.

The first stage to the campsite was undertaken on horseback.
Progress was not very fast and yours truly decided to press
ahead, but as the altitude took its toll the raison d'etre of the
horse became obvious. A slap on the rear from the arrieros
persuaded the horse to leap across the river whilst the arrieros
preferred to cross the bridge upstream. The horse was unable to
make the jump and so stopped  I didn't   and scrambled from the
river in a sodden state. From then on, there was a complete
respect by the entire party for the effects of altitude!

Camping in the Cordillera was very comfortable with the
temperature rarely falling below minus five degrees centigrade
and very pleasant evenings were spent around the campfire. The
mess tent was the scene of a pleasant "happy hour" before dinner
when we drank Pisco   a grape brandy to which we took quite a
liking   followed by an excellent meal prepared by the arrieros.
As darkness fell lights appeared from other campfires high on the
hillside where itinerant Indians were spending the night.
However, we slept well as our dogs were very capable of keeping
any light fingered intruders at bay.

Early morning: dawn was greeted with tea brought to our
tents at 6.30 am. An excellent breakfast was taken as the sun
rose and we were off again. The climb to the Punta Union was very
steep as we wound upwards along the zig zag, rock strewn path. We
passed by the very edge of glaciers below the four peaked summit
of Taulliraju  5,830m , which dominated the scene with its jagged
serrated ridges, lit up in the early sunlight.

A long time was spent on the summit of this pass, partly for
a desperately needed breather but mainly to take in the wonderful
panorama. Everywhere was silent, the snow white and glistening.
The Pass is guarded by Taulliraju, its vast glaciers tumbling
down into a deep turquoise lake far below, whilst overhead we
caught our first glimpse of a Condor soaring above the ridges.
The sun became hotter, there were deep rumblings and an avalanche
fell down the mountainside   then all was silent once more.

Once over the Pass we descended across bog land through the
Huaripampa when we returned to lush vegetation and beautiful
flowers. On the way we passed several medium sized Indian
villages where we were made very welcome. Village land is
generally owned collectively and the rural Indians live virtually
outside the money economy. Day to day life is organized on the
basis of mutual help  big jobs, such as harvesting, threshing and
house building are done with the help of neighbours, who in
return receive help when needed. In spite of their apparent
poverty, we certainly had the impression that they were a happy
and contented people. A wedding was taking place in a nearby
village and the procession passed us by on the trail, the bride
to be on horseback, the family carrying everything needed for the
festival, and grandma bringing up the rear carrying her kettle.

Along the seventy five mile length of the Cordillera rise
some twenty peaks of over 6,000m, including Peru's highest
mountain, Huascaran, with the world's largest concentration of
glaciers within the tropical zone. Our journey continued over
several high passes and we saw many fine waterfalls which tumble
over cliffs creating delightful patterns in the afternoon sun.

A very stiff climb to the Portachuelo de Rataquena and
suddenly the summit of the Pass was upon us revealing a mighty
panorama of the high peaks of Rataquena, Tocllaraju and Copa,
reaching down into the Honda Valley which was to lead us to our
destination. And then a very rare experience   just below the
summit and on very slippery ice coated cliffs we saw the Rima Rima,
a plant found only in this part of Peru. With its delicate
red flower and large leaves, it seemed more suited to a
greenhouse than to the top of a 5,000m pass. The Indians have a
special reverence for the flower, perhaps because of its success
in surviving in its hostile environment, and some wear it in
their hatbands for good fortune.

On the final descent to Rinoconda the burros seemed to sense
that their labours were at an end and proceeded with renewed
energy over limestone rock, serrated over the years by water
erosion. The river swells in winter and then recedes during the
summer to reveal the strata of the rock and strange formations.
It tumbled noisily through yet another cataract as we reached the
end of our journey to be were greeted by beer, sandwiches and
fruit before loading our equipment back onto the bus.

As we left the high hills for the last time, we looked back
at the beautiful peak of Rataquena with its summit glistening in
the sunlight and reflected on the scenery we had been privileged
to trek through, also the hospitality we had experienced from
everyone we met.
