:SETUP:
#+SETUPFILE: ./setup.org
#+TITLE: Western Gully, Black Ladders.
:END:

* Western Gully, Black Ladders
by
Ian Barton

"This is going to be a straightforward climb with no epics
or benightments. I've done the route before, it's grade IV and we
are going to make a really early start, so there is no chance of
getting benighted." Knowing grins were exchanged by the others.

The route in question was  Western Gully  in North Wales. The
climb is on a crag called  The Black Ladders  Ysgolion Duon  in
the heart of the Carneddau. Next morning I kept my resolution
about making an early start and we were away from the hut by
5.00 am. I also had a very strong partner in the form of Caveman
 Andy  so success and descent before the pubs closed seemed
assured, as we drove round to Bethesda and began the long walk up
Cwm Llafar.

The first setback occurred when we arrived at the bottom of
the gully at about 7.00 am to find that everyone else had also
got up early. I suppose the route's inclusion in "Cold Climbs"
accounts for its popularity, as people add it to their tick
lists. Two parties were already established on the first pitch
with numerous others waiting their turn at the bottom and we
could hear sounds of others higher up the gulley. Andy and I
geared up surreptitiously to one side of the crowd and when we
were ready, played our trump card. Cheating outrageously, Andy
led up the steep frozen turf to the left of the first ice pitch.
The crowd fell silent and stared at us, amazed that we should
manage to outflank them by this simple manoeuvre. Andy reached
the first stance having successfully overtaken two parties and I
climbed quickly to reach him. We were now near the front of the
queue and, moving together on the easier section that followed,
we overtook all but one pair.

Catching up with the two at the front of the queue just
below a steep section, I belayed and brought Andy up to me. The
pair in front of us had managed to get their ropes into a bit of
a tangle so we had to wait while they sorted things out. Looking
up at the continuation of the gully there was hardly any build up
of ice, with only a veneer of verglas and a dusting of powder
snow covering the rocks. Eventually the way was clear and Andy
set off up the next pitch. This was a narrow chimney with an
awkward exit at its top. Climbing in his usual fast and efficient
style he had soon reached the next stance, making it all look
easy. When it was my turn to follow I found the ground anything
but straightforward and struggled to get out of the chimney.

The team in front of us were now at grips with the famous
chockstone pitch. The leader had inserted a peg upside down in
the roof and was busily knocking all the ice off the steep wall
which is the key to avoiding the overhang formed by the
chockstone. Eventually he overcame the chockstone but took even
longer to get up the remainder of the pitch while we waited our
turn in the icy cold of the cave under the chockstone. At last he
was belayed but his second struggled on the first section out of
the cave, demolishing the remaining ice before disappearing into
the chimney above. Eventually it was my turn. I climbed easily up
to the peg but several attempts to climb the wall to one side of
the chockstone were repulsed by the lack of ice and resulted in
clattering descents to the floor of the cave. Finally I managed
to fix a wire in the roof of the cave and using this for aid, I
reached over the chockstone. Jamming my axes in the crack above
the chockstone, I heaved myself up around it.

I was now in a very precarious position in a narrow chimney,
but a few feet above me it widened and after a few rapid bridging
moves I was able to wedge myself securely. It was only then that
I noticed a peg below my feet just above the chockstone and which
I had failed to see in my previous haste. There was no prospect
of other runners nearby so I reversed the previous delicate moves
and reached down, managing to clip into the peg at full stretch.
Regaining my wedged position, I contemplated the ground above.
The narrow chimney continued with just a glaze of ice on the
walls, enough to make normal rock climbing impossible but not
enough to allow for the use of Chacals and crampons. I did not
fancy tackling any of this without some more runners but the only
obvious crack was too small to take my one channel peg. After I
had relayed my feelings about the lack of runners to Andy, he
asked two women who had just arrived in the cave if we could
borrow one of their pegs. While the peg was being sent up to me I
overheard a snatch of Andy's conversation with them.

	"Do you know Dai Lampard then?"
	"Yes, quite well, he's my husband!"

Even their smallest peg proved to be too big and eventually
I threaded a sling around a thin icicle, convincing myself that
it would hold my weight if I fell. However, there was now another
problem: the chimney was too constricted to climb with a sack.
Further contortions enabled me to remove the sack and hang it
from the icicle. As I struggled to climb above the sack, the ice
shattered and all four points of contact parted company from the
ice at once. I began to  slither down the chimney, the icicle
thread broke as my weight came onto it and I was heading down
over the chockstone onto the boulders underneath. Luckily, with
my Chacal I managed to hook the crab clipped into the peg above
the chockstone. This arrested my fall but I was now tangled up in
the ropes and the sack.  After tussling for a few minutes with
the tangle of gear while hanging on with one arm, I managed to
get sorted out and was once again safely wedged in the chimney.

A further session of digging out likely looking cracks
resulted in a hex hammered into the back of the chimney. I now
hung the sack from this and set off again up the chimney. This
time I was more careful with the ice and reached a better thread
round an icicle about twenty feet higher up. Above this the
difficulties eased slightly, the ice got thicker and I was able
to rest. At the top of the chimney there was an awkward move out
onto a slab but a hairline crack provided a good placement for a
knife blade. There was one final small bulge and I was then in a
second cave with massive spike belays to which I thankfully
lashed myself.

Looking back down the gully as I took in the rope and
started to bring Andy up, I could see that all the other parties
had given up and were abseiling off. Andy climbed whilst I
alternately took in one rope with the sacks attached and then the
other rope with Andy on it.
	"You had better get your head torch out" he said as he
arrived, "It'll be dark soon."
	Looking at my watch I saw it was nearly four o'clock! We had
been on the route for over nine hours although it had seemed far
less.

The next pitch was quite short, up a slab onto easier ground
above. In good conditions the slab is covered in ice but, on this
occasion it was just dusted with powder snow. Andy balanced up to
a peg, crampons scraping on the rock and then mantleshelved onto
the peg. A few more delicate moves above this and the climbing
was easier. When my turn came to follow I was impressed with his
efforts as I found the climbing very insecure and was glad that I
hadn't had to lead it. By this time I was completely knackered so
Andy offered to lead on. The next pitch was straightforward with
only one awkward boulder to surmount. Above this the climbing
became easier and we moved together on the upper section of the
gully to the top.

As I emerged Andy walked forward and shook my hand  it had
been a great climb.

It was a starlit night with perfect visibility.
	"There should be no problem getting off. All we have to do
is to follow the rim of the cwm round keeping it on our left and
then go down the easy slope to the bottom of the crag," I said.

We set off, keeping close to the edge so as not to lose the
way. After some time I was convinced that we had reached the
point at which we should descend into the cwm. However, I had
nagging doubts   there were lights in the valley below, where
there had no right to be any and the steep descent that I
remembered was an easy angled slope. We kept on going, eventually
reaching the bottom, but it did not look anything like Cwm
Llafar. After walking down the cwm for some time Andy shouted
that he had found a tarmaced track. Suddenly I knew where we
where. We had descended into the Ogwen valley and the lights in
front of us were in fact those of the hut!

Soon we reached the hut and walked in to hoots of derision.
This was the second week in a row that I had descended in the
dark and walked off the wrong side of the hill!
