:SETUP:
#+SETUPFILE: ./setup.org
#+TITLE: The Munros a Personal Pilgrimage.
:END:

* The Munros a Personal Pilgrimage
#+latex: \chapterauthor{Mike Jackson}

A number of small groups tackled the last few hundred feet
of ascent over slabby rock pavements and areas of stone and
gravel. The bare slopes held pockets of wind blown snow and the
clumps of grass were encased in frost and rime, forming masses of
exquisite white patterns. Eyes strained through the dense mist
for the elusive summit until we finally arrived at the ice encrusted cairn.
A full bottle of a favourite liqueur whisky was
produced   with matching glasses, a real touch of class that!
and the congratulations of everyone present were eagerly offered
and gladly received. For me it was the culmination of a personal
pilgrimage which had started long before...

My family had settled in Sheffield in 1947 and it was in the
wild moorlands and beautiful countryside of the delightful Peak
District that the foundation of my love for the hills was well
and truly laid. I first visited Scotland as a student in 1957 and
my first Scottish ascent was of Cairngorm from a wild and stormy
campsite at the head of Loch Avon. The vast scale and magnificent
wilderness of the Cairngorms made a deep and lasting impression
on me but, apart from a solitary trip to Glen Nevis, eleven years
passed by before I joined the CMC and at last found the
opportunity of visiting Scotland on a regular basis.

The Club had been founded in 1967 by Alec Barclay, an
expatriate Scotsman whose apparently unlimited energy and
enthusiasm soon attracted a keen following and ensured the Club
its future success. Vital features in the attraction of the Club
were the emphasis on individual inclination and achievement and
the complete absence of unnecessary regimentation. Mountaineering
with the Club was always enjoyed with the greatest of relish and
the away meets in particular were awaited with keen anticipation,
each one an adventure for those fortunate enough to be able to
take part.

My first Scottish club meet was to Lagangarbh in Glencoe in
1969 when the only carload of enthusiasts also included Alec
himself  first Hon. Secretary , Colin Mackie  first President ,
Chris Taylor  first Treasurer , Kate Peek  still a member twenty
years later . The highlight was a thrilling traverse of the
spectacular Aonach Eagach ridge in superb conditions of sunshine
and mist during the only all too brief clear interlude in a
weekend of torrential rain.

The first meet I organized myself was to Lochnagar the
following October and in the years to come I attended every one
of fourteen consecutive July meets in Glencoe and enjoyed visits
to many different areas of Scotland at all seasons, particularly
to the Cairngorms in the winter snows, establishing a welcome
programme of unfailing interest and excitement.

In 1972, during the Club's first Skye meet and after an
unforgettable day on the Black Cuillin, I discovered at the SMC
hut in Glen Brittle a slim volume which was to transform my hill
walking and result in a sense of commitment and direction I had
not previously experienced. It was, of course, "Munros Tables"
and a quick examination disclosed the enormous range of 3000 foot
summits in Scotland, far more than I had ever contemplated. I
had, it appeared, climbed only twenty three Munros and my
exploration of the Scottish hills had scarcely begun. The thought
of tackling them all fired my imagination and the long trail I
then began to follow was to lead me over the years to endless
hours, days and weeks of inspiration and delight.

A number of CMC members became equally attracted to the
Highlands and the intensity of our weekend forays increased both
in summer and in winter as the years rolled by, with early starts
from Sheffield on Friday morning in order to tackle our chosen
hill during the afternoon after our long journey. We would enjoy
a very full expedition indeed on Saturday and a considerable
outing on Sunday before dashing home in time to start work on
Monday morning. More remote areas provided an excuse or reason
for longer visits using bothies and youth hostels or camping in
the wilds  particularly successful and memorable expeditions
included those to the Far North, Skye, Torridon, the Cairngorms
and even a boat trip to the Western Sea Lochs. My most regular
companion became Jim Thomson whom I first met on an early
Cairngorm meet and who eventually completed his Munros in 1983 on
the very day of his seventy third birthday when I had the great
pleasure of standing with him on a remote summit in the Rough
Bounds of Knoydart. My sons Andrew, John and Christopher have
also enjoyed the hills and their arrival on the Scottish scene
brought me added joy.

In the course of climbing the Munros, an appreciation grows
of the great variety of Scottish hill scenery ranging from the
massive grandeur of the Cairngorms to the incomparable
excitements of the Skye Cuillin and from the sea views and
enchanting situations of Western Highland peaks to the dramatic
individual hills and ranges of the Northern Highlands. The quest
for the Munros takes one the length and breadth of the land and
ensures that many a fine hill is enjoyed that might not otherwise
have been attempted. The contrasts of the seasons   the wonderful
clarity of the springtime views, the sunshine, rain and greenery
of high summer, the glorious autumn colours and the superb
snowscapes of winter   all add to the unfailing interest and
variety of experience.

The planning of an expedition, the commitment to set off for
the summits in all weathers except the downright impossible, the
determination to pit one's strengths  and weaknesses  against the
demands of the task in hand  even on days of rain, storm and
blizzard that can on occasion make hill walking a taxing
exercise  all contribute to the challenge. The discomforts and
occasional hardships are invariably amply compensated by the
beauty of outstanding scenery and the majesty of the natural
world, the heady excitements of ridge and crag, the abundant and
precious wildlife and the companionship of good friends.

My ambition was to end my personal Munro trail in the
Cairngorms where I had climbed my first Highland hill thirty
years earlier   this grand area of high wilderness, long
distances and far horizons. And so it was, on a dark day in
October 1987, that I found myself on that bleak summit nine miles
from the nearest road, sharing a very special occasion with many
of the friends and fellow members of the CMC with whom I had
enjoyed so many wonderful hill days. I was particularly delighted
that my dear friend Jim and my youngest son Christopher were both
present   an age range of no less than sixty four years! I had
hoped for bright sunshine and great views but it was perhaps
appropriate that we had chosen an autumn day requiring some
measure of hillcraft.

After approaching this moment with ambivalent feelings, the
end of my long pilgrimage proved in the event to be yet one more
heartwarming experience after so many enjoyed on the hills over
the years   experiences which in relation to the Highlands could
be renewed a hundred times without fear of duplication. I have
had the good fortune of sharing my endeavours with proven friends
who also love these marvellous hills  they are too numerous to
mention individually but they know who they are and that they
enjoy my admiration and my gratitude: my heartfelt thanks to all
such friends and in particular to my fellow members of the CMC.
