:SETUP:
#+SETUPFILE: ./setup.org
#+TITLE:
:END:

The Castle book was originally conceived as part of the Club's 25th
Anniversary celebrations in 1988. I well remember long nights of
editorial discussion over the placement of a comma and the finer
points of English grammar!

2017 will be the 50th anniversary of the founding of the Club.  As
part of the celebrations the Club want to republish the book in a 21st
century format. Luckily I still have the original final drafts of all
the articles in WordPerfect format. I am aiming to recreate the book
in both pdf and .mobi (Kindle reader) formats. I will try and follow
the format of the original book as closely as possible with photos and
cartoons inserted in their original positions in the text.

I am putting the project on Github so people can contribute to the
process if they wish, but also to make the content available to a
wider audience. All the files used to create the book should be in the
repository, making it possible for others to publish the book in
different formats.

I am using Emacs [[http://org-mode.org][org-mode]] to edit the files. All the article files
are in plain text, making it easy for other people to re-use them. I
ma using org-mode to export the project in both [[http://latex-project.org/][LaTeX]] (to produce pdf)
and html (to produce mobi).

At the moment there are three git branches:
- LaTex: specific formatting for the LaTeX and pdf version.
- mobi: specific formatting for the Kindle (epub) version.
- master

Almost all of the development takes place in the LaTex and mobi branches.

At some point these two branches will be merged into the master
branch, thus creating a single file for all supported output formats.

* Enough of the geek Talk, I Just Want to Read It!
The pdf version is available as TheCastle.pdf. This is very much a
work in progress and is regenerated every time the project is
updated. At the moment I am just working on the first few chapters so
I can finalize the details of the layout and insertion of the figures.

For anyone who understands LaTeX you can edit the TheCastle.tex file
to alter the appearance of the final document. I have chosen to use
[[http://robjhyndman.com/hyndsight/xelatex/][XeLateX]] to generate the pdf file because it has better font handling
than pdfLaTeX.


Ian Barton.
