:SETUP:
#+SETUPFILE: ./setup.org
#+TITLE: Foreword.
#+OPTIONS: title:nil
:END:
#+latex: \includepdf{/home/ian/Documents/emacs/thecastle/images/frontcover.pdf}
#+latex: \setcounter{tocdepth}{2}
#+latex: \tableofcontents

* Foreword
#+latex: \chapterauthor{Alf Gregory}
The chapters in this book will bring back many personal memories and
make us think of the great days we have spent in the hills, for most
of us have had mountain adventures we shall never forget. These might
be toiling up the final slopes of Mount Everest, battling against wind
and rain on Kinder Scout or leading a hard route on Lakeland rock.

There are times when it is sheer hell and we wonder why we are there
at all, but on other days it is so fantastically beautiful we realise
there can be no other way of life, for the joy of mountaineering is a
mixture of so many things.

Living close to the hills, as many of us do, is our greatest privilege
and we can sometimes feel sorry for people who do not have the good
fortune to share our glorious environment. However, the important
thing is to use this to the full, cherishing and enjoying all its
natural beauty, but at the same time accepting the challenge the
higher mountains offer, for in return they will give us unforgettable
days of adventure.

It is in the companionship of an organization like The Castle
Mountaineering Club that the mountain life can be enjoyed to the
full. The articles in this book prove that and show what a wonderful
twenty one years it has been for this Club. The next twenty one should
bring even more successful climbing and hill wandering.
