:SETUP:
#+SETUPFILE: ./setup.org
#+TITLE: Preface.
:END:

:SETUP:
#+SETUPFILE: ./setup.org
#+TITLE: Preface.
:END:

* Preface
#+latex: \author{ byThe Editors}


The Castle Mountaineering Club of Sheffield was founded in
1967 by a small group of local enthusiasts. Twenty one years
later, the range of activities has been extended greatly from
humble beginnings on local Edges, with members now active on the
crags and in mountain areas both at home and abroad. Climbing
standards have improved markedly and in recent years members have
been responsible for many new routes.

This anthology has been compiled as a celebration of the
Club's twenty first birthday and demonstrates the wealth of
interests and activities encouraged by the Club and enjoyed by
its members. Every article and photograph has been contributed by
Club members, and without the active help and support of so many,
the preparation of this book would have been impossible. We would
like to thank all the contributors, not least our long suffering
illustrator Dubbo for her drawings. Dubbo assures us that her
illustrations are based on characters which are entirely
fictitious and that any resemblence to members of the CMC is
purely intentional!

The production costs could not have been met without the
many donations and pledges received from members and supporters
of the Club. A list of acknowledgements appears elsewhere and we
would especially like to express our grateful thanks to Alfred
Gregory for his Foreword and to our main sponsors, The Woodcock
Group, for their faith in the success of the project and their
invaluable financial support.

The articles are arranged more or less chronologically, thus
highlighting the developments which have taken place during the
Club's history. Each contribution is a personal account of the
exploits, successes and near disasters of Club members and those
who read this volume will surely find in it a reflection of their
own experiences on the crags and hills. For every Club character
portrayed, the reader will surely know someone who fits the
description. Even those who are not mountaineers will enjoy
sharing the many excitements and activities described, and the
spirit of fun and friendship with which they have been undertaken
by members of the Club. -

Whether or not you prefer to savour the articles in
sequence, we believe that you will enjoy a good read.

Mike Anderson\\
Steve France\\
John Barnard\\
Mike Jackson\\
Ian Barton

November 1988
