:SETUP:
#+SETUPFILE: ./setup.org
#+TITLE:
#+TITLE: A Cautionary Winter's Tale.
:END:

* A Cautionary Winter's Tale
#+latex: \chapterauthor{Dave Kime}


#+HTML: <p>
#+HTML: <em>by Dave Kime</em>
#+HTML: </p>

It was the Club's Easter Meet in Glenshee 1978. Base camp
was established at our now traditional wild campsite by the
Clunie Water on the Braemar side of the Cairnwell. Good Friday
saw Harry, Charles, Anne, Jenny and myself crammed into the Maxi
with packs and camping gear for four days. The car was left in
the ski car park and a note  containing, in accordance with
official recommendations, details of party and destination  was
left at the ticket office - the official Mountain Rescue Centre.
We struggled, with full packs, up the chair lift and off to Loch
Vrotachan. Anne appeared somewhat nervous and apprehensive - she
said it was because she hadn't done much skiing, but in
retrospect I suspect it was well justified apprehension at the
thought of spending three nights with Harry and Charles.

The weather worsened as we skinned  up to Carn a'Gheoidh,
and by Loch nan Eun spindrift was hurtling across the frozen
waters. Hardly a suitable campsite, but by dropping to the north
we found enough shelter by a peat hag to sort gear and pitch
camp. The peat was rock hard, so the tent was anchored only to
pegs buried in snow and well trampled.  Water was found at the
bottom of an  eight feet deep pot hole in the snow  with rather
delicate access. The two parties disappeared into their tents for
the night and emerged only when driven by overwhelming natural
necessity. Gales and snow swept around all night, occasionally
punctuated by  mysterious noises from the other tent. Even a cry
of help would not get us out tonight! Meanwhile, unbeknown to us,
back in civilization, police forces in five counties were
mobilising.

Come morning, the tent had survived and so had Anne. A sunny
start had us doing the Beinn Iutharns but we were soon back in
clag and Charles was having problems with his new high-tech
sticky skins which had taken a dislike to the cold weather. Gales
rose again that night and rising above them were intermittent
muffled screams. We pulled the hoods of our ducks over our heads
and pretended not to hear.

The tent had shrunk by next morning to half its former size
as the weight of snow pressed in. Charles and Harry assured us
that Anne was alright   she was less sure. Four of us skinned up
to Carn an Righ followed by Charles towing his skinless skis -
he'd make a good doggie-walker! A superb run in powder snow down
to Gleann Mor made it all worthwhile. Back at camp, the bags were
getting damp and by next morning only the tips of the tent poles
were visible. With some difficulty, the pegs were unburied and
with full packs we had a great ski down to the Baddoch Burn  then
after a last skin up to Loch Vrotachan, we joined the crowds on
the Cairnwell run.

The car was still there, but Anne was convinced that someone
had been through her handbag but not taken any money - three
nights with Harry and Charles does take a little getting over!
Mugs of coffee in the cafe where we heard that Sheffield had been
cut off from the world, airports closed and the Glenshee Mountain
Rescue called out. Well, it had been a bit wild. A little later I
wandered over to the counter to report our safe return.

"Er, yes, er, just a, er, minute" said the lad  and
disappeared to return with the manager and Leader of the Mountain
Rescue Team.

Over the next few weeks the story was pieced together. By
nine at night the white Maxi stood in splendid isolation in the
middle of the empty car park. The police were informed and the
car number dispatched for the Swansea computer to work on.
Meanwhile, back at base Kate and Al had arrived and were settling
in for the night. Kate was rudely disturbed from a privy squat by
powerful torches, Land Rovers and the full might of the Braemar
police force. Somewhat shaken by this disturbance Kate was
interrogated about the whereabouts of the Kime party. The officer
did not react very kindly when told that these malingerers were
camping in the hills. Meanwhile two mountain rescue teams had
assembled and the ski tows were brought into operation to search
for the "lost" skiers.

The Swansea computer had informed the Braemar and Sheffield
constabularies of the identity of the owner of the Maxi.

At Hallamshire Close, Sheffield, the Kime house was empty
so the neighbours were knocked up for questioning.

"Oh, they're camping in Scotland somewhere."

"Yes, we've just found their car - nothing in it but an old
pair of wellington boots and a ladies handbag." ,!
Leaving our friends to the vision of their eccentric
neighbours barefoot on the mountain, the officers departed. An
hour later, our friends phoned West Bar police station in
Sheffield when they remembered where Jenny's father worked.
Across the Pennines, the University night porter was awoken from
his duties and questioned as to the whereabouts of the Professor
of Engineering. Lancaster Constabulary found his house empty as
well.

"He's in Scotland" said the neighbours   "at the cottage."

No way were the Inverness Constabulary in Fort William going
to drive two hours to that address at that time of night: a phone
call to their local contact would have to suffice. Campbell
Morrison was dragged from behind the bar at the Clan to drive
three miles, wake up the Professor and bring him to the phone.

"They're camping in the hills and they know what they're
doing. Call your rescue off!"

The message got back to Braemar and all teams were stood
down. The Braemar police, on returning to base, stopped by to
rouse Kate and Al again in order to tell them in no uncertain
terms that Dr. Kime was to report to the police station
IMMEDIATELY he got back.

Next morning the staff were back  at work at the ski centre
and as the ticket office opened, the lad put his hand in his
pocket.

"Och, Hamish, a laddie left me this note yesterd....." As
Hamish said: "The lads dealt with him - he won't forget again in
a hurry."

Back to base camp in the glen where we discovered that our
tent had disappeared, then found the shreds neatly folded and
packed in Charles' tent. Kate and Al returned from a day of
ticking and passed on the message.  ,   -  Down to Braemar.

"My name's Kime, I believe you want to question me in
connection with..."

"Och, that fiasco on Friday, come on in."

Somewhere in all this there must be a moral   about parked
cars, about leaving  notes to the  police, and rescue teams being
called out unnecessarily, and of training and certificates  and
of the freedom to roam the hills unhindered and to  take
responsibility for one's own safety and actions?
