:SETUP:
#+SETUPFILE: ./setup.org
#+TITLE: Traverse of the Cuillin Ridge.
:END:

* Traverse of the Cuillin Ridge
#+latex: \chapterauthor{Andy Smith}


#+begin_html
<p>
<em>by Andy Smith</em>
</p>
#+end_html

We roused ourselves from our brief but comfortable bivouac
on the  Bealach a' Gharbh Choire, the pale dawn heralding a
perfect Skye day.  Way below us to the east we could see that
remote and magical spot  below the fine peak of Sgurr nan Stri
where the River Coruisk flows  into Loch Scavaig. To the south,
the Small Isles   Soay, Canna, Rhum and  Eigg   were visible
across the calm Hebridean sea, with the fascinating  and shapely
peaks of Rhum in particular attracting the attention.

It was 3.45 am on Tuesday 27th May 1975, the occasion being
the Club's  Spring Bank Holiday meet to the Black Cuillin, the
party  comprising Ronny Hindmoor, John and Lesley Evans, Sean
Jennings,  Andrew Hothersall, Martin Coggins, Anne Pendlebury and
myself. We had  left Glen Brittle at eight the previous evening
and scrambled  up Sron na Ciche via  Collie's Route , reaching the
top in time to see a  gorgeous sunset. Later we had romped along
the crest of the ridge in  bright moonlight, reaching its
southernmost peak, Gars Bheinn, before  heading back to our
bivouac site. Now, with the stars fading rapidly, we  packed our
sacks and climbed to the top of Sgurr Dubh na Da Bheinn  where,
having warmed ourselves up and reached a superb viewpoint, we
paused for breakfast.

Ahead, the jagged crest of the Main Ridge encircled the head of Loch
Coruisk to its final peak and our ultimate objective - Sgurr nan
Gillean a long day's scrambling away but tantalisingly close beyond
the coire. We soon reached the famous Thearlaich Dubh Gap, the first
and most difficult rock pitch of the day. We abseiled into the Gap and
the pitch out of the Gap was well led, the rest of us thrutching up
one way or another - the rock was polished and strenuous and we took
close on an hour to get our party of eight across. We left our sacks
whilst detouring slightly from the Main Ridge to take in Skye's
highest point, the paramount Sgurr Alasdair 3257 ft .

The next section, around Coire Lagan, is possibly the
finest stretch of the whole trip: Sgurr Thearlaich, an abseil
down to  Bealach Mhic Coinnich, the surprising Collie's Ledge to
Sgurr Mhic  Coinnich and the magnificent scramble over An Stac
culminating in  the unique Inaccessible Pinnacle. We soloed up
the moderate but very  exposed east ridge of the Pinnacle and
abseiled down the short west face. It was now  11 am and getting
very hot  time for lunch.

The ridge becomes sustained, brilliant scrambling:
Banachdich, Thormaid, Ghreadaidh, Mhadaidh, Bidein Druim nan
Ramh, An  Caisteal, Bhairnich, Bruach na Frithe: the roll call of
evocative  Gaelic names familiar to every Skye afficionado. Each
Munro has a  number of tops which all have to be visited, and
even on a clear day,  route finding is not straightforward in
places. It must be very tricky  in mist, compounded by the
occurrence of magnetic rock to confuse the  compass.

We were now beginning to get tired and dehydrated. It is
well  known that there is no water on the ridge and we were
carrying large  water bottles, but on such a hot windless day,
our supplies of liquid  had dwindled rapidly. Fortunately there
were still a few snow patches  lingering from the winter to
provide us with a welcome supply of cool  melt water  otherwise
we might well have had to give up.

The Bhasteir  Tooth is usually done via  Naismith's Route , an
easy but very exposed  pitch and the last place on the ridge
where a rope is needed.  Unfortunately, when we arrived a large
army party was having a  prolonged abseiling epic on the route,
so we circumnavigated it by  dropping into the Fionn Choire to
the north before tackling Am Basteir itself.

We arrived at the final peak, Sgurr nan Gillean, at 7.30 pm,
nearly  eighteen hours  including the bivouac  after leaving Gars
Bheinn, not  a bad time considering the size of the party and the
sweltering  conditions.

After staying  together all along the ridge we now split up,
some wanting to  hurry down to the Sligachan Inn to ensure a
pint, the aesthetes preferring to linger and enjoy a perfect
evening in the hills,  chatting, admiring and photographing the
views and consuming the last  remnants of food.

At last we reluctantly left the tops and wearily set out
along the seemingly interminable track back to Sligachan,
reaching it just  before 11.00 pm, twenty seven hours after
leaving Glen Brittle: twenty one peaks, many of  them Munros,
fifteen miles of ridge with at least 10,000 feet of ascent and
the roughest, wildest, mountaineering Scotland has to offer. It
was my  longest day out in the British mountains - and the best!
