:SETUP:
#+SETUPFILE: ./setup.org
#+TITLE: High Spirits.
:END:

* High Spirits
#+latex: \chapterauthor{Steve France}


#+begin_export html
<p>
<em>by Steve France</em>
</p>
#+end_export

Some years ago, whilst visiting the battle site of Culloden
Field on a damp and misty September day, I was subjected to a
feeling of utter dread.  Subconscious emotions told me, "You must
get away!" People could wander round the graves from clan to clan
for hours but my whole visit lasted less than twenty minutes.  A
year later in the middle of the vast winter landscape of the
Cairngorms, I suffered the same experience.

It was a typical Castle plod, made worse by dense cloud and
deteriorating conditions, but our spirits were high even though
Chris Holmes, Dick Savage and myself felt more at home on rock
than playing the mountain man. The steep slog towards the
Cairngorm plateau was no fun, especially when the skiers were
gently gliding past on the ski tow whilst making sarcastic
comments and giving us sneering looks. Our replies ranged from
"Yes, we do enjoy walking up" to "No, it's not tiring when you're
fit".

Before our language became offensive we saw an ideal
opportunity for one upmanship. By climbing a high banking of snow
at the side of the tow run, we could jump and grab the unoccupied
tow bars!

Weee!... up we went and after a short period spent adjusting
the angle of our boots on the snow, a perfect glide was obtained
on our Vibram skis! Protests were heard further down the tow from
"paying" participants and we raised our overmitts in reply  they
could not see the two fingers inside, but I think that the
message was plain enough!

Once over the wind swept edge of the plateau we were on our
own and left to enjoy the beauty of the mountain solitude. The
clouds were white with snow as we came to the col beside Lochan
Buidhe. The mountains merged with the snow into total whiteness,
so bright that our duvets appeared translucent. The silence was
oppressive except for the crunching of the snow. I remember
vividly the way we walked, as if in a slow motion action replay.
This was my first and only "white out", the only reality was
the person in front until suddenly a snow bank resolved itself
into focus in front of my eyes. It was not the snow bank that I
saw but a hole in the snow,  approximately one metre square.
We entered, and as the tunnel opened out, were stunned with
surprise by the ice village which greeted our eyes. It was
without doubt the Ritz of all snow holes with room after room
each connected to the other and complete with its own table,
chairs, raised bed and shelving systems... all made out of ice.
It must have been a distant relic from a winter survival course
at Glenmore Lodge but the unnatural silence, together with the
ambient light that soaked through the ice walls, transformed the
shelter into a mortuary of past memories. Imagining ghosts,
goblins and yetis, we ran out of the tunnel and back to the
welcoming "white".

Another mile and our high spirits changed.  I can remember
approaching the final slopes trying to find an excuse to turn
back, but there was no rational explanation why, and so we went
on. The cairn was found quite by accident  we were standing on
it!  because the snow covered all but the brass plaque on top
which shows the various peaks and directions. Even though we had
reached our goal, the summit of Ben Macdui gave us no pleasure.
There was no vista to enjoy, only grey dread and an urge to go
home quickly. The usual summit rest, comprising a bite to eat
whilst soaking in self-satisfaction, was limited to a quick photo
before we legged it back down the mountain.

The campsite talk that night re-lived the arduous knee deep
slush and the "white out", but we never talked about Ben Macdui.
I am sure that strange perception of malevolence was shared
subconsciously between us, although at the time, I never gave it
much thought.

Recently I was reading a book entitled "Scottish Ghost
Stories" and to my surprise, discovered that there is an alleged
ghoul on Ben Macdui called "The Grey Man". Although never seen,
it has been responsible for campers fleeing for their lives,
leaving tents and equipment behind, totally convinced of their
impending doom if they remained there any longer.
Gruesome stuff!
