:SETUP:
#+SETUPFILE: ./setup.org
#+TITLE: Round Edale Walk.
:END:

* Round Edale Walk or "Who Went Where and Who Said What?"
#+latex: \chapterauthor{Jack Ashcroft}


#+HTML: <p>
#+HTML: <em>by Jack Ashcroft</em>
#+HTML: </p>

An innocent enough walk around Edale.
"You can't get lost up there," was the bar room atmosphere
at half past ten on Thursday evening.
Well you can. If you don't take your map and compass,
whistle, torch, contact lenses   if appropriate  and it's
raining, the cloud banks are low, the gale force on the Beaufort
Scale is approaching eight and you don't check your position
regularly and keep the group together...

Ten of us left Mam Nick car park at 8.45 am to tackle the
Walk clockwise. Before Lords Seat the furious Westerly had us
reeling and two returned to the car park. Eight then battled on
for Brown Knoll   a little spread out   but on arrival at the
trig point we were only six in number. We got cold standing there
in the wind, straining our eyes through the mist for the other
two, both ladies. Concern.

#+begin_verse
"Secretaries are dispensable."  E
#+end_verse


...mutter...  mutter...  mutter...  J
#+begin_verse
"Let's push off in the true spirit of mountaineering
comradeship."
#+end_verse

#+begin_verse
"Here they are."
#+end_verse


Two figures loomed out of the mist. But it wasn't them.
#+begin_verse
"We haven't seen them    we followed the path all the way."
#+end_verse

So we were eight again, but a different eight.
#+begin_verse
"Hope they are together."
"She's never been up here before   hasn't got a map."  E
"She knows the topography   she's got common sense."  E
#+end_verse

#+begin_verse
"Your decision."
"Let's go on and see what happens."
#+end_verse
We walk on to Edale Cross.

#+begin_verse
"They're here."
"You're disqualified   missed out Brown Knoll check point."

#+end_verse

#+begin_verse
"Rubbish, we followed the right hand side of the dyke.
Pointless going off route to the trig point."
"We really will keep together now."
#+end_verse

And we basically did... to the shelter of the boulders below
The Pagoda.

#+begin_verse
"I've just been talking to someone up there who I
thought was one of us until I pushed my nose into his
face."
"We need a Kinder sixth sense move to the top of
Grindsbrook. We'll stop there for a bite to eat."
"OK, it's alright. Don't bother to get your map out."
So ten set swiftly off into the wind, rain and mist, full of
confidence.
#+end_verse

#+begin_verse
"It's rough going. Too much up and down the groughs."
"Stop. Let's think where we are."
"More to the right."
"Up to the left."
"We've lost them now."
#+end_verse
Five of us left.

#+begin_verse
"Let's stick together."
"The stream is going north. This must be the Kinder
River."
"This way."
"Move south."
"No. Move over. Still more east."
"It's like caving above ground."
"Drop into the groughs at the head of Grindsbrook."
"This is it."
"Damn! It's Crowden Brook, not Grindsbrook."
"We've gone round in circles."
"No we haven't! Just a horseshoe   a mile to progress
half a mile."
"Are we stopping to dry out tights and long johns?"
"I wear socks the same as every one else."
"The feminist touch."
"Right, now for Grindsbrook, I bet someone's there."
#+end_verse
Someone was.
#+begin_verse
"I've been here five or ten minutes. Dropped into the
groughs head of Grindsbrook on a compass bearing. I
haven't a map."
#+end_verse

It was 12.38 pm.

#+begin_verse
"Don't go down there. It's best to wait until we get to
Golden Clough if you want to go down."
Six of us stood at the top of Golden Clough.
"Who's for going down?"
"Well..."
"Tea in Coppers."
"Newcastle Brown in The Nags."
"You can tell who are the walkers!"
"You can tell who are the climbers!"
"Who's doing what?"   "That's it then."
Two went down for refreshment. Four went on. Too swiftly again, I
fear.
"We haven't seen the trig point."
"It's over there."
"This is the head of Jaggers."
"Doesn't seem deep enough to me."
#+end_verse
Neither was it.

#+begin_verse
"That's the Snake road down there and we are walking
out."
"It's Blackden."
"Turn around for Crookstone Knoll."
"I'll watch her down there and you up here   keep in
contact."
"You can get off the plateau but you may be fifteen
miles from where you want to be."
#+end_verse

And so off the plateau towards Crookstone Barn. Two lasses and
two lads.

#+begin_verse
"Those trees must be two of the toughest in the Peak."
"Down the Roman Road to meet the car at The Cheshire
Cheese."
"There's a quicker route than that."
"Oh! Someone has moved the fence."
#+end_verse

And so we were on the road at Edale End. The two lads approached
Lose Hill under the railway near Fiddle Clough. It was 3.20 pm.
The two lasses walked along the road to meet their transport at
The Cheshire Cheese.

Lose Hill wasn't in fact traversed by both the lads: one
followed the track around the south side of Lose Hill into the
wind. Slow tiring progress.

#+begin_verse
"I waited here out of the wind so we'd be together to
traverse Mam Tor. It looks vicious up there."

#+end_verse
And so it was. Racing cloud touching the summit, the light
gone, crawling on hands and knees. It was 5.05 pm. The rest of
the cars had gone.
#+begin_verse
"I've never been in wind like that before."
#+end_verse

And who sheltered at Kinder Downfall for lunch and never saw
Crowden Brook or Grindsbrook at all? What a Who dunnit! Oh the
freedom of the hills! u  I call an EGM. The motion:
#+begin_verse
"The CMC should affiliate to the British Orienteering
Association."

#+end_verse
Proposed   Guess Who?
Seconded   Get Lost! Plus ten supporting Kinder members.
