:SETUP:
#+SETUPFILE: ./setup.org
#+TITLE: Welsh Rarebit.
:END:

* Welsh Rarebit
#+latex: \chapterauthor{Steve France}


#+begin_html
<p>
<em>by Steve France</em>
</p>
#+end_html

Bill Hine was spread out on the back seat clutching his
mouth in a desperate attempt not to laugh, as I stood outside the
car saying:
	"Yes Mr Policeman, No Mr Policeman, forty miles per hour I
think, Mr Policeman..."

Chris Wright, sitting in the front, thought the grovelling
was far more entertaining than the car stereo so, turning it
down, he was just in time to hear:

	"And I won't do it again Mr Policeman".

I entered the car soon after and shut the door with a clunk.
The resulting burst of laughter must have been overheard by the
rookie who was walking back to his police car.  His pride had
already been severely dented during his frantic efforts to catch
us up. However, the score was now one all and we were on our way
to Anglesey.

Since the opening of the M56, the journey is considerably
quicker than it used to be, but there's still time to reflect
back to those Welsh days when every route turned out to be a
classic or an epic adventure that gets worse every time you told
it.  A portion of my memory is always reserved for Idwal Slabs
and the mass ascents by the Club in big boots and cags.  The
Castle's hard core climbing team twelve years ago was a motley
crew led by Sheila MacDonald and her never ending fag and with
John Ward bringing up the rear, seen but never heard.  A few
years later some new faces came onto the scene and the climbing
grades started to rise to 5b 5c.  This was the time Bill was
introduced to the Castle  by Dave Bates and Keith Naylor  and
Dick Savage  Tricky Dicky  who was an earlier Castle climber left
for India to achieve inner transcendental harmony.  In those days
a Castle ascent of  Cenotaph Corner ,  Cemetary Gates  and  Vector  was
an achievement, but alas these routes along with many more have
been down graded to "just good classics". For me the mountain
classics will always hold that extra magic which the modern
routes lack at the moment. Maybe it's the atmosphere or could it
be just a pleasant memory?

All three of us in the car were quite adept at the modern
routes but on this occasion, after many months pestering, I
finally convinced Chris to have a go at a sea cliff classic for a
change. The car ground to a halt on the gravel surface of South
Stack car park. The air was damp due to the sea spray in the
blustery wind so that by the time we had our rucksacks and ropes
packed the "What am I doing here?" syndrome was setting in.

	"OK, where's the crag?" asked Chris unenthusiastically.

After walking in a rough north easterly direction, for
twenty minutes, we were above the sea cliffs of Gogarth. Past
visits to the cliff had resulted in climbing the usual  Pentathol ,
 Gogarth ,  Cordon Bleu  and  Central Park  but unfortunately a large
proportion of the routes suffer from access problems during high
tide.  According to Sods Law, no matter what time you arrive it
will always be high tide! Today was no exception.  Reading the
Guide Book about high tide approaches was depressing and when we
consulted a group of "knowledgeable" climbers  who were festering
between some boulders they said, "You have no chance for at least
three hours". So, acting on this information, we set off to Wen
Slab. Maybe we could come back later or tomorrow but now a new
goal had raised our enthusiasm -  Quartz Icicle  or  Wen . Anything
except  Dream of White Horses , not because  Dream  is a poor route -
quite the opposite. For any first time visit it is highly
recommended, but I had climbed it three times before with
different parties and there had been no time left for anything
else.

On arrival it was decided to walk down the gully on the
right as you face out to sea for the spectacular view of the zawn
thus giving an impressive vista of all the routes. There it was
in all its splendour - Froggatt Edge on a Sunday afternoon in
summer! It was like Butlins Holiday Camp in the late sixties.
Quartz Icicle  was being climbed!  Wen  also! There were climbers
everywhere... and no less than three parties on  Dream  alone! The
overall scene was stunning and very reminiscent of Baggy Slabs
with  Midnight Cowboy ,  Kinky Boots  and  Sexilegs   all being climbed
at the same time.

Chris was not impressed, as our only option was to trek back
to Gogarth and wait for the tide rather than wait for the crowds
to subside on Wen Slab.  Back we went, but this time we geared up
at the top of the descent path and climbed down the small gully
to the bottom of the cliffs. It was far better to wait here than
to brood at the top  at least we could look at the sea level
traverse and climb along at the earliest possible moment.

When we arrived it was high and dry by a long way, in fact
it looked passable at most times except for maximum high tide.
Our feelings were mixed: happy to be able to do at last the route
we had set out for and cheesed off because we had turned into
bigger pratts than the two "knowledgeable" climbers we met
earlier.

Traversing across the bottom of the cliff took no more than
a few minutes. The ropes were quickly uncoiled and we were ready
to climb  Big Groove .  Gogarth's  Big Groove  is not particularly
difficult by today's standards and rose to fame during the "Hard
Rock " days when its popularity increased tenfold.  Its total
height of 340 feet is climbed in three pitches of 5a 5c  and 5a
grading. Although this route had been climbed before by many
Castle members, for me it was the one that had got away.

Bill took the lead on the first pitch and burned up the rock
to disappear over a ledge some fifty feet up. Time lingered on
with relatively little movement from the rope.
	"Are you belayed yet?" I shouted, only to be met by silence.

The silence went on for some twenty minutes broken only by
the occasional jerk of the rope, until finally we heard the faint
call:
	"Climb when yer ready".

Chris set off and I followed some five minutes later,
puzzled by the apparent speed of his ascent, especially above the
ledge where the problem seemed to have occurred.

Upon reaching the ledge the puzzle became worse because Bill
and Chris were sitting only twenty feet away with no obvious hard
or even slightly difficult climbing between us. However, there
was a seagull!

	"Don't disturb it, its nesting" whispered Bill, looking
quite concerned that I might kick it off.

In fact, as I was traversing an absolutely desperate wall
over the gull I did feel like kicking it off, especially when all
it could do was look up at me with a "look at that silly bugger "
expression on its beak!

Once on the belay ledge my immediate attention was on the
second pitch that I was about to lead. From the stance, very
little could be seen apart from the seepage lines of wet rock,
with the mist and sea spray blowing up the groove. I was unable
to convince Chris that this was the pitch he ought to lead, so I
set off. A short wall led to the groove itself which was
deceptively steep. In fact it gets steeper each time I think
about it! I must confess that I'm not a particularly strong
climber and I usually try and make up for that deficiency by
technique  however, that does not always work, especially on
routes like  Axle Attack  and  Body Machine  where without strength
and stamina you just don't stand a chance of a clean ascent.
Anyway, by now the groove was seeping with water and had got
very, very, steep   even steep enough to justify my owning up to
using the peg! But it was only for a few seconds, honest!

I knew that hesitation below the peg would prove disastrous,
because slowly but surely my forearms were beginning to ache with
their solidification.  The veins pulsed and stuck out like
fossilised tree trunks, to be shortly followed by the involuntary
uncurling of the fingers.  With one last effort I managed to
reach the bottom of a flake, and thrust my fingers right round
it, preventing them from uncurling. How many times do you get
into the situation when you're twenty feet above your last
protection, pumped out of your head and the flake does not allow
the insertion of any useful gear?

The only option was to continue up the flake where it formed
an apex and lasso a sling over it.  What sounded like a good idea
turned out to be a nightmare, as I laybacked up the flake higher
and higher until the last runner was just a distant memory.
However, there was one consoling factor - if I fell off now there
would at least be a strong possibility I would land on that gull!

Almost there, but something didn't seem right. Could it have
been the groaning and creaking of the flake? After some thought I
realised that the whole flake was bending and flexing with every
layback thrust. Nervously peering round for a closer
investigation, I saw the true thickness of the flake to be only
half an inch.
	"It must be stronger that it looks, having remained on the
route for so long" I thought, in a desperate attempt to convince
myself that everything was just great.  Lassoing the tip of the
flake with a sling, I remembered the verse by Ben King:
	"Nowhere to fall but off, Nowhere to stay but on."
	What a load of garbage!

The karabiner clicked home and the tension eased as I boldly
bridged up to the right below the belay stance and heaved my body
onto a ledge. Standing up on the ledge was another matter but the
whole performance is too embarrassing to describe here. The ledge
was just right for one, and when Bill arrived soon after it was -
for want of a better word - "cosy".  When Chris arrived, however,
the ledge became a writhing mass of arms, legs, ropes and
runners.

Chris had intended to lead through but the weather had
turned increasingly nasty. Over the last hour, during the ascent
of the second pitch, the clag had set in and spray was howling
upwards in the vortex created by the groove. The whole effect
made it look as though it were raining upwards!  The decision had
been made earlier that if I managed the second pitch we would go
on, but if not we would abandon the route. Unfortunately there
was no turning back now.

Chris set off up the final groove very slowly, as by now
everything was totally saturated, even Bill and I. Rather than
start singing "My favourite things" I began to think about
sitting in front of a roaring open fire in the pub that night,
swilling the amber nectar and talking of the day's events
especially giving Bill a roasting for wasting a good hour by
being polite to the seagull!

By now we were well and truly frozen stiff with all
enthusiasm long gone. The rope very slowly came to its end and
assuming it was time to climb, I set off. I must admit and said
to Chris at the time that his lead on that final pitch in the
conditions that prevailed was superhuman. The fact that he
managed to stay on at all is beyond me - let alone climb the
soaking lichen pads and shattered rock flakes.  At long last, the
top was made by all three followed by the quickest descent  via
the path!  on record.

There was no fire in the pub but there was a pool table
well, you can't have everything.
