:SETUP:
#+SETUPFILE: ./setup.org
#+TITLE: From Toothbrush to Sledgehammer.
:END:

* From Toothbrush to Sledgehammer
#+latex: \chapterauthor{Steve France}


#+HTML: <p>
#+HTML: <em>by Steve France</em>
#+HTML: </p>

The winter of 1985 86 was The Castle Mountaineering Club's
biggest climbing triumph - yet not many members know the true
extent of the Club's success. More new routes were claimed on one
crag than probably all The Castle's other first ascents put
together.

The "secret" Quarry is situated on the right as you travel
up the road from Stoney Middleton and is accessed via a gate and
track which leads to the quarry base. The main wall, which is
almost vertical, extends some hundred feet in height to a huge
ledge which effectively splits the face, forming an upper tier of
fifty feet.

When Steve France, Chris Wright and Ian French entered
Horseshoe Quarry for the first time, the true potential of the
place was finally realised. Its loose and dangerous condition was
enough to put anyone off, but what was required was a bit of
vision and imagination and between the three of them there was
certainly that. The Big Question was, would they be wasting their
time developing an area which nobody would bother to visit? Only
time would tell, but the first thing to do was to clean the place
up and to make it worth climbing on. It didn't take long to
realise that any glory to be had would not come cheaply.

At first the usual gardening equipment was used -  wire
brush, toothbrush, small trowel and broddling stick   but it
didn't take long to realise that these tools were totally
inadequate. Steve had started to clean a small ledge on his first
new route and after shovelling at least half a ton of rubble
discovered he no longer had a small ledge but a huge belay stance
for about a dozen people. Furthermore, the bigger the ledge got,
the shorter the route became, as he slowly filled up the quarry
bottom with its debris. Steve later became known as the Mad
Axeman due to his mean short pick-axe which he used for levering
off small flakes, boulders, in fact anything that moved  or
didn't   but that is another story .

In the early days of development, huge amounts of rubble and
rock were detached in order to clean up the cliff face. This was
not just confined to the routes themselves but the rock was
generally cleared all over in a desperate attempt to make the
place safe and more appealing: apart from that, "spoffing" blocks
happens to be bloody good fun. The biggest trundle was a gigantic
hanging pinnacle weighing at least five tons, situated half way
up the wall on the left hand side and poised ready to fall at any
time. The Mad Axeman picked away at its footing like a
masochistic dentist but alas failed in the attempt. The next day,
not to be outdone, the giant tooth was attacked again but this
time with a large pick and a six foot long crowbar. The resulting
"bavoooooom" must have been heard for miles. Well worth the
effort!

   The most controversial decision was the use of bolt
protection . Due to an instinctive desire to live, bolts were
necessary having regard to the quarry's lack of natural fault
lines, which meant that there were few  if any runner
placements. Even pegs were bottoming after only an inch of
penetration. Sounds painful! By strategic placing, it was in fact
possible to use only four bolts to protect a hundred feet of
climbing  these were pre-placed during the last stage of the
cleaning operation.

The actual leading of the routes was  in accordance with
modern day ethics  done without practice or top rope - to make
the ascent as pure as possible.  Even this was not pure enough
for Steve Ralph who at a later stage amazed us all with his
"clean lead on sight" policy.

Developing the upper tier also had its problems due to the
lack of abseil points at the top.  So Chris and Steve had to
sledge hammer a series of belay stakes into the ground each day
these they buried under piles of stones to prevent others from
using them until the routes had been claimed. The top was very
reminiscent of Millstone with its loose shale and grovelling
finishes and so platforms were dug out of the sloping earth to
enable everyone to actually finish the route instead of wondering
if the protection was good while free falling! This also had a
second advantage in that it prevented a constant dustfall down
the rock face, previously inevitable whenever the wind blew.

As with the main face, there was plenty of loose rock to
detach on the top tier. Unfortunately it had a tendency to roll
over the lip of the main ledge and go crashing down the main wall
below. Although this was two for the price of one, everyone had
to know where everyone else was and anyone who decided to go
walkabout did so at his own risk.

By the time of the New Year, Ian had finished four of the main
lines on the lower wall, including  Megalithic Man  and  Ancient
Rhythm . Steve had completed his excavation of the ledge and named
the ensuing route  Nice Face, Shame About the Ledge . Chris, who by
now had the misfortune to be working for a living, had half cleaned
a route on the lower face but then decided to join Steve
with the Upper Tier development with his eyes set on Mr Blue
Sky .

However, all good things must come to an end and the word
was finally out, bringing visitors to the quarry. The self indulgence
of eating the cherry cake might have to be shared!

The fun now began in earnest because many routes had been
cleaned but not led - including the one Chris had started
cleaning earlier and this was the route which another group was
eyeing up first! There was no time to lose but Chris was at work
and not available until the weekend, so the honours went to Steve
who climbed the route and called it   Shot Yer Bolt . Not
surprisingly, Chris was displeased, so Steve gave him one of his
unclimbed cleaned routes as a peace offering - subsequently named
 White Dove . During the next few weeks a spate of ascents were
made and the pressure to complete new routes was reduced.

Ian Barton and Steve Ralph now entered the quarry with the
promise from the trio that there were new routes to be had,
especially at the lower end of the gradings. Ian wasn't impressed
but made a token gesture of several rock routes and an ice gully
at the back of the quarry. Unfortunately  or fortunately!  only
one of Ian's routes were attributed to him in the guide book and
Steve Ralph received the honours instead.  In fact Steve R. was
"given" quite a few routes he knew nothing about, due less to the
generosity of the new ascentionists but more to their
embarrassment in owning up to them! This may be unfair to Steve
R., but perhaps due to the loose, dirty, and dangerous routes
which he led, he asked for it!

There is a true report of a pair of French girls who
recently visited the quarry, and after no success in climbing the
higher grades, were kindly directed towards the   Bimbo ...
routes. After struggling and cleaning for an hour and a half they
finally screamed "Quelle Masse de Garbage" and walked away
feeling totally disillusioned with British Climbing.

After four months of digging, the novelty finally wore off
and the very sight of a wire brush or shovel prompted a baulk of
revulsion. Altogether, thirty five routes were climbed by The
Castle with sixteen of them being attributed to Steve Ralph.  As
for the original trio, they all succeeded in their secret desire
to bag their first 6b virgin ascent. With all the best lines
gone, The Castle left the quarry to the droves of scavengers that
poured into it. The potential for new routes was still as strong
as ever, although much of the remaining surface contained loose
rubbish. It was nice to see the interest that the quarry provoked
but in the long term it will probably suffer from enthusiastic
young leaders willing to climb anything, however loose, for the
sake of immortality.

On visiting the quarry today you will usually find several
parties climbing there. The original vision of Ian, Steve and
Chris has finally reaped its reward. The rock dries exceptionally
quickly and, coupled with the bolt protection, makes it an ideal
crag for the winter or wet. Unfortunately the routes at the lower
end of the scale tend to reflect the nick name Horseshit Quarry
but if you do routes of 5b or harder you may well be very
pleasantly surprised, although probably knackered as well.
