:SETUP:
#+SETUPFILE: ./setup.org
#+TITLE: Grit Biter.
:END:

* Grit Biter
#+latex: \chapterauthor{Frank Mellor}


#+begin_export html
<p>
<em>by Frank Mellor</em>
</p>
#+end_export


In the summer of '86 siege tactics were employed on a
twenty foot route at Stanage. Although the attempt was
unsuccessful the style in which it was made inspired this poetic
gem.

I watched a wind blown figure
Below a roof of rock,
A holey orange tee shirt
And a badly darned left sock.

His right leg and his forearms
Are quivering fit to bust,
In another two short seconds
He will surely Bite the Dust!

His Springer spaniel and his wife
Both watch, devoid of hope,
For the sixteenth time that afternoon
He sags onto the rope.

"I'll give it one last try," he says,
The chance must not be missed
And so into that loathsome crack
He jams his bleeding fist.

A few choice words he mutters
And wears determined frown,
But odd EBs kick at the air
And he hangs there, upside down!

The watchers roar in sheer delight
To see this latest antic,
I fear this beastly little route
Will drive our hero frantic.
He will return once more he vows
To do it in the wet!
Perhaps, with helmet back to front,
He'll catch you Marmoset.
